package world

// AllCountries contains seed data for all 195 countries.
// Data is based on real-world statistics, normalized for game balance.
// Resources are on a 0-100 scale. Adjacency includes both land and sea neighbors.
var AllCountries = []CountrySeed{
	// ============================================================
	// S-TIER: Superpowers (8)
	// ============================================================
	{ISO3: "USA", Name: "United States", Continent: "North America", Tier: TierS, Resources: Resources{Oil: 85, Minerals: 70, Food: 95, Tech: 95, Manpower: 80}, Latitude: 38.90, Longitude: -77.04, CapitalName: "Washington D.C.", Population: 331000000, TerrainTheme: "urban", Adjacency: []string{"CAN", "MEX", "CUB", "BHS"}},
	{ISO3: "CHN", Name: "China", Continent: "Asia", Tier: TierS, Resources: Resources{Oil: 50, Minerals: 80, Food: 80, Tech: 90, Manpower: 100}, Latitude: 39.91, Longitude: 116.39, CapitalName: "Beijing", Population: 1400000000, TerrainTheme: "urban", Adjacency: []string{"RUS", "MNG", "PRK", "VNM", "LAO", "MMR", "IND", "NPL", "BTN", "KAZ", "KGZ", "TJK", "AFG", "PAK"}},
	{ISO3: "RUS", Name: "Russia", Continent: "Europe", Tier: TierS, Resources: Resources{Oil: 95, Minerals: 90, Food: 60, Tech: 70, Manpower: 55}, Latitude: 55.76, Longitude: 37.62, CapitalName: "Moscow", Population: 144000000, TerrainTheme: "arctic", Adjacency: []string{"NOR", "FIN", "EST", "LVA", "LTU", "POL", "BLR", "UKR", "GEO", "AZE", "KAZ", "CHN", "MNG", "PRK", "JPN"}},
	{ISO3: "IND", Name: "India", Continent: "Asia", Tier: TierS, Resources: Resources{Oil: 25, Minerals: 60, Food: 75, Tech: 80, Manpower: 100}, Latitude: 28.61, Longitude: 77.21, CapitalName: "New Delhi", Population: 1380000000, TerrainTheme: "urban", Adjacency: []string{"PAK", "CHN", "NPL", "BTN", "BGD", "MMR", "LKA"}},
	{ISO3: "BRA", Name: "Brazil", Continent: "South America", Tier: TierS, Resources: Resources{Oil: 55, Minerals: 75, Food: 90, Tech: 55, Manpower: 75}, Latitude: -15.79, Longitude: -47.88, CapitalName: "Brasilia", Population: 212000000, TerrainTheme: "forest", Adjacency: []string{"ARG", "URY", "PRY", "BOL", "PER", "COL", "VEN", "GUY", "SUR", "GUF"}},
	{ISO3: "JPN", Name: "Japan", Continent: "Asia", Tier: TierS, Resources: Resources{Oil: 5, Minerals: 10, Food: 40, Tech: 98, Manpower: 45}, Latitude: 35.68, Longitude: 139.69, CapitalName: "Tokyo", Population: 126000000, TerrainTheme: "island", Adjacency: []string{"KOR", "RUS", "CHN", "TWN"}},
	{ISO3: "DEU", Name: "Germany", Continent: "Europe", Tier: TierS, Resources: Resources{Oil: 10, Minerals: 30, Food: 60, Tech: 95, Manpower: 40}, Latitude: 52.52, Longitude: 13.41, CapitalName: "Berlin", Population: 83000000, TerrainTheme: "urban", Adjacency: []string{"FRA", "NLD", "BEL", "LUX", "CHE", "AUT", "CZE", "POL", "DNK"}},
	{ISO3: "GBR", Name: "United Kingdom", Continent: "Europe", Tier: TierS, Resources: Resources{Oil: 40, Minerals: 20, Food: 50, Tech: 90, Manpower: 35}, Latitude: 51.51, Longitude: -0.13, CapitalName: "London", Population: 67000000, TerrainTheme: "island", Adjacency: []string{"IRL", "FRA", "NLD", "BEL", "NOR"}},

	// ============================================================
	// A-TIER: Major Powers (20)
	// ============================================================
	{ISO3: "KOR", Name: "South Korea", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 5, Minerals: 15, Food: 35, Tech: 95, Manpower: 30}, Latitude: 37.57, Longitude: 126.98, CapitalName: "Seoul", Population: 51700000, TerrainTheme: "urban", Adjacency: []string{"PRK", "JPN", "CHN"}},
	{ISO3: "FRA", Name: "France", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 10, Minerals: 25, Food: 70, Tech: 88, Manpower: 35}, Latitude: 48.86, Longitude: 2.35, CapitalName: "Paris", Population: 67000000, TerrainTheme: "urban", Adjacency: []string{"DEU", "BEL", "LUX", "CHE", "ITA", "ESP", "AND", "MCO", "GBR"}},
	{ISO3: "CAN", Name: "Canada", Continent: "North America", Tier: TierA, Resources: Resources{Oil: 80, Minerals: 85, Food: 70, Tech: 80, Manpower: 20}, Latitude: 45.42, Longitude: -75.70, CapitalName: "Ottawa", Population: 38000000, TerrainTheme: "arctic", Adjacency: []string{"USA"}},
	{ISO3: "AUS", Name: "Australia", Continent: "Oceania", Tier: TierA, Resources: Resources{Oil: 30, Minerals: 90, Food: 65, Tech: 75, Manpower: 15}, Latitude: -35.28, Longitude: 149.13, CapitalName: "Canberra", Population: 25700000, TerrainTheme: "desert", Adjacency: []string{"IDN", "NZL", "PNG"}},
	{ISO3: "SAU", Name: "Saudi Arabia", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 100, Minerals: 30, Food: 15, Tech: 50, Manpower: 20}, Latitude: 24.71, Longitude: 46.68, CapitalName: "Riyadh", Population: 34800000, TerrainTheme: "desert", Adjacency: []string{"JOR", "IRQ", "KWT", "QAT", "ARE", "OMN", "YEM"}},
	{ISO3: "TUR", Name: "Turkey", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 15, Minerals: 50, Food: 65, Tech: 60, Manpower: 45}, Latitude: 39.93, Longitude: 32.86, CapitalName: "Ankara", Population: 84000000, TerrainTheme: "mountain", Adjacency: []string{"GRC", "BGR", "GEO", "ARM", "AZE", "IRN", "IRQ", "SYR"}},
	{ISO3: "IDN", Name: "Indonesia", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 40, Minerals: 60, Food: 70, Tech: 40, Manpower: 85}, Latitude: -6.21, Longitude: 106.85, CapitalName: "Jakarta", Population: 270000000, TerrainTheme: "island", Adjacency: []string{"MYS", "TLS", "PNG", "AUS", "PHL", "SGP"}},
	{ISO3: "MEX", Name: "Mexico", Continent: "North America", Tier: TierA, Resources: Resources{Oil: 60, Minerals: 55, Food: 60, Tech: 45, Manpower: 55}, Latitude: 19.43, Longitude: -99.13, CapitalName: "Mexico City", Population: 128000000, TerrainTheme: "desert", Adjacency: []string{"USA", "GTM", "BLZ"}},
	{ISO3: "ITA", Name: "Italy", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 10, Minerals: 20, Food: 65, Tech: 80, Manpower: 30}, Latitude: 41.90, Longitude: 12.50, CapitalName: "Rome", Population: 60000000, TerrainTheme: "urban", Adjacency: []string{"FRA", "CHE", "AUT", "SVN", "SMR", "VAT"}},
	{ISO3: "ESP", Name: "Spain", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 5, Minerals: 25, Food: 65, Tech: 70, Manpower: 25}, Latitude: 40.42, Longitude: -3.70, CapitalName: "Madrid", Population: 47000000, TerrainTheme: "urban", Adjacency: []string{"FRA", "PRT", "AND", "MAR", "GBR"}},
	{ISO3: "IRN", Name: "Iran", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 90, Minerals: 55, Food: 45, Tech: 50, Manpower: 45}, Latitude: 35.69, Longitude: 51.39, CapitalName: "Tehran", Population: 83000000, TerrainTheme: "desert", Adjacency: []string{"IRQ", "TUR", "ARM", "AZE", "TKM", "AFG", "PAK"}},
	{ISO3: "EGY", Name: "Egypt", Continent: "Africa", Tier: TierA, Resources: Resources{Oil: 45, Minerals: 30, Food: 40, Tech: 35, Manpower: 50}, Latitude: 30.04, Longitude: 31.24, CapitalName: "Cairo", Population: 102000000, TerrainTheme: "desert", Adjacency: []string{"LBY", "SDN", "ISR", "PSE"}},
	{ISO3: "PAK", Name: "Pakistan", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 15, Minerals: 35, Food: 55, Tech: 30, Manpower: 75}, Latitude: 33.69, Longitude: 73.04, CapitalName: "Islamabad", Population: 220000000, TerrainTheme: "mountain", Adjacency: []string{"IND", "CHN", "AFG", "IRN"}},
	{ISO3: "NGA", Name: "Nigeria", Continent: "Africa", Tier: TierA, Resources: Resources{Oil: 75, Minerals: 40, Food: 55, Tech: 25, Manpower: 70}, Latitude: 9.06, Longitude: 7.49, CapitalName: "Abuja", Population: 206000000, TerrainTheme: "forest", Adjacency: []string{"BEN", "CMR", "TCD", "NER"}},
	{ISO3: "ISR", Name: "Israel", Continent: "Asia", Tier: TierA, Resources: Resources{Oil: 5, Minerals: 15, Food: 40, Tech: 95, Manpower: 10}, Latitude: 31.77, Longitude: 35.23, CapitalName: "Jerusalem", Population: 9200000, TerrainTheme: "desert", Adjacency: []string{"LBN", "SYR", "JOR", "EGY", "PSE"}},
	{ISO3: "POL", Name: "Poland", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 5, Minerals: 40, Food: 60, Tech: 60, Manpower: 25}, Latitude: 52.23, Longitude: 21.01, CapitalName: "Warsaw", Population: 38000000, TerrainTheme: "plains", Adjacency: []string{"DEU", "CZE", "SVK", "UKR", "BLR", "LTU", "RUS"}},
	{ISO3: "ZAF", Name: "South Africa", Continent: "Africa", Tier: TierA, Resources: Resources{Oil: 10, Minerals: 85, Food: 50, Tech: 50, Manpower: 30}, Latitude: -25.75, Longitude: 28.19, CapitalName: "Pretoria", Population: 59000000, TerrainTheme: "plains", Adjacency: []string{"NAM", "BWA", "ZWE", "MOZ", "SWZ", "LSO"}},
	{ISO3: "UKR", Name: "Ukraine", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 15, Minerals: 55, Food: 75, Tech: 45, Manpower: 30}, Latitude: 50.45, Longitude: 30.52, CapitalName: "Kyiv", Population: 44000000, TerrainTheme: "plains", Adjacency: []string{"RUS", "BLR", "POL", "SVK", "HUN", "ROU", "MDA"}},
	{ISO3: "NLD", Name: "Netherlands", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 20, Minerals: 10, Food: 55, Tech: 85, Manpower: 10}, Latitude: 52.37, Longitude: 4.89, CapitalName: "Amsterdam", Population: 17400000, TerrainTheme: "plains", Adjacency: []string{"DEU", "BEL", "GBR"}},
	{ISO3: "SWE", Name: "Sweden", Continent: "Europe", Tier: TierA, Resources: Resources{Oil: 5, Minerals: 60, Food: 45, Tech: 85, Manpower: 8}, Latitude: 59.33, Longitude: 18.07, CapitalName: "Stockholm", Population: 10400000, TerrainTheme: "arctic", Adjacency: []string{"NOR", "FIN", "DNK"}},

	// ============================================================
	// B-TIER: Regional Powers (40)
	// ============================================================
	{ISO3: "THA", Name: "Thailand", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 15, Minerals: 30, Food: 75, Tech: 45, Manpower: 40}, Latitude: 13.76, Longitude: 100.50, CapitalName: "Bangkok", Population: 69800000, TerrainTheme: "forest", Adjacency: []string{"MMR", "LAO", "KHM", "MYS"}},
	{ISO3: "ARG", Name: "Argentina", Continent: "South America", Tier: TierB, Resources: Resources{Oil: 35, Minerals: 45, Food: 85, Tech: 45, Manpower: 25}, Latitude: -34.60, Longitude: -58.38, CapitalName: "Buenos Aires", Population: 45000000, TerrainTheme: "plains", Adjacency: []string{"BRA", "URY", "PRY", "BOL", "CHL"}},
	{ISO3: "COL", Name: "Colombia", Continent: "South America", Tier: TierB, Resources: Resources{Oil: 50, Minerals: 40, Food: 60, Tech: 35, Manpower: 30}, Latitude: 4.71, Longitude: -74.07, CapitalName: "Bogota", Population: 50900000, TerrainTheme: "forest", Adjacency: []string{"VEN", "BRA", "PER", "ECU", "PAN"}},
	{ISO3: "MYS", Name: "Malaysia", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 45, Minerals: 40, Food: 55, Tech: 55, Manpower: 20}, Latitude: 3.14, Longitude: 101.69, CapitalName: "Kuala Lumpur", Population: 32400000, TerrainTheme: "forest", Adjacency: []string{"THA", "IDN", "SGP", "BRN", "PHL"}},
	{ISO3: "PHL", Name: "Philippines", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 35, Food: 55, Tech: 40, Manpower: 50}, Latitude: 14.60, Longitude: 120.98, CapitalName: "Manila", Population: 109600000, TerrainTheme: "island", Adjacency: []string{"IDN", "MYS", "TWN", "VNM"}},
	{ISO3: "VNM", Name: "Vietnam", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 30, Minerals: 35, Food: 65, Tech: 40, Manpower: 50}, Latitude: 21.03, Longitude: 105.85, CapitalName: "Hanoi", Population: 97300000, TerrainTheme: "forest", Adjacency: []string{"CHN", "LAO", "KHM"}},
	{ISO3: "BGD", Name: "Bangladesh", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 15, Food: 60, Tech: 25, Manpower: 70}, Latitude: 23.81, Longitude: 90.41, CapitalName: "Dhaka", Population: 164700000, TerrainTheme: "plains", Adjacency: []string{"IND", "MMR"}},
	{ISO3: "NOR", Name: "Norway", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 85, Minerals: 30, Food: 30, Tech: 80, Manpower: 5}, Latitude: 59.91, Longitude: 10.75, CapitalName: "Oslo", Population: 5400000, TerrainTheme: "arctic", Adjacency: []string{"SWE", "FIN", "RUS", "GBR", "DNK"}},
	{ISO3: "CHE", Name: "Switzerland", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 0, Minerals: 10, Food: 35, Tech: 90, Manpower: 5}, Latitude: 46.95, Longitude: 7.45, CapitalName: "Bern", Population: 8700000, TerrainTheme: "mountain", Adjacency: []string{"DEU", "FRA", "ITA", "AUT", "LIE"}},
	{ISO3: "AUT", Name: "Austria", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 25, Food: 45, Tech: 75, Manpower: 8}, Latitude: 48.21, Longitude: 16.37, CapitalName: "Vienna", Population: 9000000, TerrainTheme: "mountain", Adjacency: []string{"DEU", "CZE", "SVK", "HUN", "SVN", "ITA", "CHE", "LIE"}},
	{ISO3: "BEL", Name: "Belgium", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 15, Food: 45, Tech: 75, Manpower: 8}, Latitude: 50.85, Longitude: 4.35, CapitalName: "Brussels", Population: 11600000, TerrainTheme: "plains", Adjacency: []string{"FRA", "DEU", "NLD", "LUX"}},
	{ISO3: "CHL", Name: "Chile", Continent: "South America", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 80, Food: 50, Tech: 50, Manpower: 12}, Latitude: -33.45, Longitude: -70.67, CapitalName: "Santiago", Population: 19100000, TerrainTheme: "mountain", Adjacency: []string{"ARG", "BOL", "PER"}},
	{ISO3: "PER", Name: "Peru", Continent: "South America", Tier: TierB, Resources: Resources{Oil: 20, Minerals: 65, Food: 55, Tech: 30, Manpower: 20}, Latitude: -12.05, Longitude: -77.04, CapitalName: "Lima", Population: 32970000, TerrainTheme: "mountain", Adjacency: []string{"ECU", "COL", "BRA", "BOL", "CHL"}},
	{ISO3: "VEN", Name: "Venezuela", Continent: "South America", Tier: TierB, Resources: Resources{Oil: 95, Minerals: 40, Food: 35, Tech: 25, Manpower: 18}, Latitude: 10.49, Longitude: -66.88, CapitalName: "Caracas", Population: 28400000, TerrainTheme: "forest", Adjacency: []string{"COL", "BRA", "GUY"}},
	{ISO3: "IRQ", Name: "Iraq", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 90, Minerals: 25, Food: 30, Tech: 20, Manpower: 25}, Latitude: 33.31, Longitude: 44.37, CapitalName: "Baghdad", Population: 40200000, TerrainTheme: "desert", Adjacency: []string{"TUR", "SYR", "JOR", "SAU", "KWT", "IRN"}},
	{ISO3: "KWT", Name: "Kuwait", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 92, Minerals: 10, Food: 5, Tech: 45, Manpower: 3}, Latitude: 29.38, Longitude: 47.99, CapitalName: "Kuwait City", Population: 4300000, TerrainTheme: "desert", Adjacency: []string{"IRQ", "SAU"}},
	{ISO3: "ARE", Name: "United Arab Emirates", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 88, Minerals: 15, Food: 10, Tech: 65, Manpower: 8}, Latitude: 24.45, Longitude: 54.37, CapitalName: "Abu Dhabi", Population: 9900000, TerrainTheme: "desert", Adjacency: []string{"SAU", "OMN"}},
	{ISO3: "QAT", Name: "Qatar", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 85, Minerals: 10, Food: 5, Tech: 55, Manpower: 2}, Latitude: 25.29, Longitude: 51.53, CapitalName: "Doha", Population: 2900000, TerrainTheme: "desert", Adjacency: []string{"SAU", "BHR"}},
	{ISO3: "SGP", Name: "Singapore", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 0, Food: 10, Tech: 92, Manpower: 4}, Latitude: 1.35, Longitude: 103.82, CapitalName: "Singapore", Population: 5700000, TerrainTheme: "island", Adjacency: []string{"MYS", "IDN"}},
	{ISO3: "FIN", Name: "Finland", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 0, Minerals: 35, Food: 35, Tech: 82, Manpower: 5}, Latitude: 60.17, Longitude: 24.94, CapitalName: "Helsinki", Population: 5500000, TerrainTheme: "arctic", Adjacency: []string{"SWE", "NOR", "RUS", "EST"}},
	{ISO3: "DNK", Name: "Denmark", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 20, Minerals: 10, Food: 55, Tech: 80, Manpower: 5}, Latitude: 55.68, Longitude: 12.57, CapitalName: "Copenhagen", Population: 5800000, TerrainTheme: "plains", Adjacency: []string{"DEU", "SWE", "NOR"}},
	{ISO3: "IRL", Name: "Ireland", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 10, Food: 50, Tech: 78, Manpower: 4}, Latitude: 53.35, Longitude: -6.26, CapitalName: "Dublin", Population: 5000000, TerrainTheme: "plains", Adjacency: []string{"GBR"}},
	{ISO3: "PRT", Name: "Portugal", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 0, Minerals: 20, Food: 50, Tech: 60, Manpower: 8}, Latitude: 38.72, Longitude: -9.14, CapitalName: "Lisbon", Population: 10300000, TerrainTheme: "plains", Adjacency: []string{"ESP"}},
	{ISO3: "GRC", Name: "Greece", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 20, Food: 50, Tech: 55, Manpower: 8}, Latitude: 37.98, Longitude: 23.73, CapitalName: "Athens", Population: 10700000, TerrainTheme: "island", Adjacency: []string{"ALB", "MKD", "BGR", "TUR"}},
	{ISO3: "CZE", Name: "Czech Republic", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 30, Food: 50, Tech: 70, Manpower: 8}, Latitude: 50.08, Longitude: 14.44, CapitalName: "Prague", Population: 10700000, TerrainTheme: "plains", Adjacency: []string{"DEU", "POL", "SVK", "AUT"}},
	{ISO3: "ROU", Name: "Romania", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 20, Minerals: 35, Food: 60, Tech: 45, Manpower: 15}, Latitude: 44.43, Longitude: 26.10, CapitalName: "Bucharest", Population: 19200000, TerrainTheme: "plains", Adjacency: []string{"UKR", "MDA", "HUN", "SRB", "BGR"}},
	{ISO3: "NZL", Name: "New Zealand", Continent: "Oceania", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 15, Food: 65, Tech: 70, Manpower: 4}, Latitude: -41.29, Longitude: 174.78, CapitalName: "Wellington", Population: 5100000, TerrainTheme: "island", Adjacency: []string{"AUS"}},
	{ISO3: "KAZ", Name: "Kazakhstan", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 80, Minerals: 70, Food: 45, Tech: 30, Manpower: 12}, Latitude: 51.17, Longitude: 71.43, CapitalName: "Nur-Sultan", Population: 18800000, TerrainTheme: "plains", Adjacency: []string{"RUS", "CHN", "KGZ", "UZB", "TKM"}},
	{ISO3: "ETH", Name: "Ethiopia", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 30, Food: 50, Tech: 15, Manpower: 55}, Latitude: 9.02, Longitude: 38.75, CapitalName: "Addis Ababa", Population: 115000000, TerrainTheme: "mountain", Adjacency: []string{"ERI", "DJI", "SOM", "KEN", "SSD", "SDN"}},
	{ISO3: "DZA", Name: "Algeria", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 70, Minerals: 35, Food: 25, Tech: 25, Manpower: 25}, Latitude: 36.75, Longitude: 3.04, CapitalName: "Algiers", Population: 43900000, TerrainTheme: "desert", Adjacency: []string{"MAR", "TUN", "LBY", "NER", "MLI", "MRT"}},
	{ISO3: "MAR", Name: "Morocco", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 50, Food: 40, Tech: 30, Manpower: 22}, Latitude: 34.02, Longitude: -6.83, CapitalName: "Rabat", Population: 36900000, TerrainTheme: "desert", Adjacency: []string{"DZA", "ESP", "MRT"}},
	{ISO3: "KEN", Name: "Kenya", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 25, Food: 45, Tech: 30, Manpower: 30}, Latitude: -1.29, Longitude: 36.82, CapitalName: "Nairobi", Population: 53800000, TerrainTheme: "plains", Adjacency: []string{"ETH", "SOM", "TZA", "UGA", "SSD"}},
	{ISO3: "MMR", Name: "Myanmar", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 15, Minerals: 40, Food: 55, Tech: 15, Manpower: 30}, Latitude: 19.76, Longitude: 96.07, CapitalName: "Naypyidaw", Population: 54400000, TerrainTheme: "forest", Adjacency: []string{"IND", "CHN", "LAO", "THA", "BGD"}},
	{ISO3: "TWN", Name: "Taiwan", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 0, Minerals: 10, Food: 25, Tech: 95, Manpower: 15}, Latitude: 25.03, Longitude: 121.57, CapitalName: "Taipei", Population: 23600000, TerrainTheme: "island", Adjacency: []string{"CHN", "JPN", "PHL"}},
	{ISO3: "HUN", Name: "Hungary", Continent: "Europe", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 20, Food: 55, Tech: 55, Manpower: 8}, Latitude: 47.50, Longitude: 19.04, CapitalName: "Budapest", Population: 9700000, TerrainTheme: "plains", Adjacency: []string{"AUT", "SVK", "UKR", "ROU", "SRB", "HRV", "SVN"}},
	{ISO3: "PRK", Name: "North Korea", Continent: "Asia", Tier: TierB, Resources: Resources{Oil: 5, Minerals: 50, Food: 25, Tech: 20, Manpower: 35}, Latitude: 39.02, Longitude: 125.75, CapitalName: "Pyongyang", Population: 25800000, TerrainTheme: "mountain", Adjacency: []string{"KOR", "CHN", "RUS"}},
	{ISO3: "CUB", Name: "Cuba", Continent: "North America", Tier: TierB, Resources: Resources{Oil: 10, Minerals: 30, Food: 40, Tech: 30, Manpower: 10}, Latitude: 23.11, Longitude: -82.37, CapitalName: "Havana", Population: 11300000, TerrainTheme: "island", Adjacency: []string{"USA", "MEX", "JAM", "HTI"}},
	{ISO3: "LBY", Name: "Libya", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 85, Minerals: 20, Food: 10, Tech: 15, Manpower: 5}, Latitude: 32.90, Longitude: 13.18, CapitalName: "Tripoli", Population: 6900000, TerrainTheme: "desert", Adjacency: []string{"TUN", "DZA", "NER", "TCD", "SDN", "EGY"}},
	{ISO3: "AGO", Name: "Angola", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 70, Minerals: 55, Food: 35, Tech: 15, Manpower: 20}, Latitude: -8.84, Longitude: 13.23, CapitalName: "Luanda", Population: 32900000, TerrainTheme: "plains", Adjacency: []string{"COD", "COG", "ZMB", "NAM"}},
	{ISO3: "COD", Name: "DR Congo", Continent: "Africa", Tier: TierB, Resources: Resources{Oil: 15, Minerals: 90, Food: 45, Tech: 10, Manpower: 50}, Latitude: -4.32, Longitude: 15.31, CapitalName: "Kinshasa", Population: 89600000, TerrainTheme: "forest", Adjacency: []string{"COG", "CAF", "SSD", "UGA", "RWA", "BDI", "TZA", "ZMB", "AGO"}},

	// ============================================================
	// C-TIER: Standard (80) — representative selection
	// ============================================================
	{ISO3: "SVK", Name: "Slovakia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 20, Food: 45, Tech: 55, Manpower: 5}, Latitude: 48.15, Longitude: 17.11, CapitalName: "Bratislava", Population: 5500000, TerrainTheme: "mountain", Adjacency: []string{"CZE", "POL", "UKR", "HUN", "AUT"}},
	{ISO3: "SVN", Name: "Slovenia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 15, Food: 40, Tech: 60, Manpower: 2}, Latitude: 46.06, Longitude: 14.51, CapitalName: "Ljubljana", Population: 2100000, TerrainTheme: "mountain", Adjacency: []string{"ITA", "AUT", "HUN", "HRV"}},
	{ISO3: "HRV", Name: "Croatia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 15, Food: 45, Tech: 50, Manpower: 4}, Latitude: 45.81, Longitude: 15.98, CapitalName: "Zagreb", Population: 4100000, TerrainTheme: "plains", Adjacency: []string{"SVN", "HUN", "SRB", "BIH", "MNE"}},
	{ISO3: "SRB", Name: "Serbia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 25, Food: 50, Tech: 40, Manpower: 6}, Latitude: 44.79, Longitude: 20.47, CapitalName: "Belgrade", Population: 6900000, TerrainTheme: "plains", Adjacency: []string{"HUN", "ROU", "BGR", "MKD", "XKX", "MNE", "BIH", "HRV"}},
	{ISO3: "BGR", Name: "Bulgaria", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 25, Food: 50, Tech: 40, Manpower: 6}, Latitude: 42.70, Longitude: 23.32, CapitalName: "Sofia", Population: 6900000, TerrainTheme: "mountain", Adjacency: []string{"ROU", "SRB", "MKD", "GRC", "TUR"}},
	{ISO3: "LTU", Name: "Lithuania", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 10, Food: 45, Tech: 50, Manpower: 3}, Latitude: 54.69, Longitude: 25.28, CapitalName: "Vilnius", Population: 2800000, TerrainTheme: "plains", Adjacency: []string{"LVA", "BLR", "POL", "RUS"}},
	{ISO3: "LVA", Name: "Latvia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 10, Food: 40, Tech: 48, Manpower: 2}, Latitude: 56.95, Longitude: 24.11, CapitalName: "Riga", Population: 1900000, TerrainTheme: "plains", Adjacency: []string{"EST", "LTU", "BLR", "RUS"}},
	{ISO3: "EST", Name: "Estonia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 10, Food: 35, Tech: 72, Manpower: 1}, Latitude: 59.44, Longitude: 24.75, CapitalName: "Tallinn", Population: 1300000, TerrainTheme: "plains", Adjacency: []string{"LVA", "RUS", "FIN"}},
	{ISO3: "BLR", Name: "Belarus", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 25, Food: 50, Tech: 40, Manpower: 8}, Latitude: 53.90, Longitude: 27.57, CapitalName: "Minsk", Population: 9400000, TerrainTheme: "plains", Adjacency: []string{"RUS", "UKR", "POL", "LTU", "LVA"}},
	{ISO3: "GEO", Name: "Georgia", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 20, Food: 40, Tech: 35, Manpower: 4}, Latitude: 41.69, Longitude: 44.80, CapitalName: "Tbilisi", Population: 3700000, TerrainTheme: "mountain", Adjacency: []string{"RUS", "TUR", "ARM", "AZE"}},
	{ISO3: "ARM", Name: "Armenia", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 25, Food: 30, Tech: 40, Manpower: 3}, Latitude: 40.18, Longitude: 44.51, CapitalName: "Yerevan", Population: 3000000, TerrainTheme: "mountain", Adjacency: []string{"GEO", "AZE", "TUR", "IRN"}},
	{ISO3: "AZE", Name: "Azerbaijan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 70, Minerals: 25, Food: 35, Tech: 30, Manpower: 8}, Latitude: 40.41, Longitude: 49.87, CapitalName: "Baku", Population: 10100000, TerrainTheme: "plains", Adjacency: []string{"RUS", "GEO", "ARM", "IRN", "TUR"}},
	{ISO3: "UZB", Name: "Uzbekistan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 25, Minerals: 40, Food: 45, Tech: 20, Manpower: 22}, Latitude: 41.30, Longitude: 69.28, CapitalName: "Tashkent", Population: 34000000, TerrainTheme: "desert", Adjacency: []string{"KAZ", "KGZ", "TJK", "AFG", "TKM"}},
	{ISO3: "TKM", Name: "Turkmenistan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 75, Minerals: 20, Food: 20, Tech: 15, Manpower: 5}, Latitude: 37.95, Longitude: 58.38, CapitalName: "Ashgabat", Population: 6000000, TerrainTheme: "desert", Adjacency: []string{"KAZ", "UZB", "AFG", "IRN"}},
	{ISO3: "KGZ", Name: "Kyrgyzstan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 35, Food: 35, Tech: 15, Manpower: 5}, Latitude: 42.87, Longitude: 74.59, CapitalName: "Bishkek", Population: 6500000, TerrainTheme: "mountain", Adjacency: []string{"KAZ", "CHN", "TJK", "UZB"}},
	{ISO3: "TJK", Name: "Tajikistan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 30, Food: 30, Tech: 10, Manpower: 7}, Latitude: 38.56, Longitude: 68.77, CapitalName: "Dushanbe", Population: 9500000, TerrainTheme: "mountain", Adjacency: []string{"KGZ", "UZB", "AFG", "CHN"}},
	{ISO3: "AFG", Name: "Afghanistan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 60, Food: 25, Tech: 5, Manpower: 25}, Latitude: 34.53, Longitude: 69.17, CapitalName: "Kabul", Population: 38900000, TerrainTheme: "mountain", Adjacency: []string{"PAK", "IRN", "TKM", "UZB", "TJK", "CHN"}},
	{ISO3: "NPL", Name: "Nepal", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 15, Food: 40, Tech: 15, Manpower: 18}, Latitude: 27.72, Longitude: 85.32, CapitalName: "Kathmandu", Population: 29100000, TerrainTheme: "mountain", Adjacency: []string{"IND", "CHN"}},
	{ISO3: "LKA", Name: "Sri Lanka", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 20, Food: 45, Tech: 30, Manpower: 15}, Latitude: 6.93, Longitude: 79.85, CapitalName: "Colombo", Population: 21900000, TerrainTheme: "island", Adjacency: []string{"IND"}},
	{ISO3: "KHM", Name: "Cambodia", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 15, Food: 50, Tech: 15, Manpower: 10}, Latitude: 11.56, Longitude: 104.93, CapitalName: "Phnom Penh", Population: 16700000, TerrainTheme: "forest", Adjacency: []string{"THA", "LAO", "VNM"}},
	{ISO3: "LAO", Name: "Laos", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 25, Food: 45, Tech: 10, Manpower: 5}, Latitude: 17.97, Longitude: 102.63, CapitalName: "Vientiane", Population: 7300000, TerrainTheme: "forest", Adjacency: []string{"CHN", "VNM", "KHM", "THA", "MMR"}},
	{ISO3: "MNG", Name: "Mongolia", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 65, Food: 30, Tech: 15, Manpower: 3}, Latitude: 47.92, Longitude: 106.92, CapitalName: "Ulaanbaatar", Population: 3300000, TerrainTheme: "plains", Adjacency: []string{"RUS", "CHN"}},
	{ISO3: "JOR", Name: "Jordan", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 25, Food: 20, Tech: 35, Manpower: 8}, Latitude: 31.95, Longitude: 35.93, CapitalName: "Amman", Population: 10200000, TerrainTheme: "desert", Adjacency: []string{"ISR", "SYR", "IRQ", "SAU", "PSE"}},
	{ISO3: "LBN", Name: "Lebanon", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 10, Food: 25, Tech: 40, Manpower: 5}, Latitude: 33.89, Longitude: 35.50, CapitalName: "Beirut", Population: 6800000, TerrainTheme: "mountain", Adjacency: []string{"SYR", "ISR"}},
	{ISO3: "SYR", Name: "Syria", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 35, Minerals: 15, Food: 30, Tech: 20, Manpower: 12}, Latitude: 33.51, Longitude: 36.29, CapitalName: "Damascus", Population: 17500000, TerrainTheme: "desert", Adjacency: []string{"TUR", "IRQ", "JOR", "ISR", "LBN"}},
	{ISO3: "YEM", Name: "Yemen", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 40, Minerals: 15, Food: 20, Tech: 10, Manpower: 20}, Latitude: 15.37, Longitude: 44.21, CapitalName: "Sana'a", Population: 29800000, TerrainTheme: "desert", Adjacency: []string{"SAU", "OMN"}},
	{ISO3: "OMN", Name: "Oman", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 65, Minerals: 15, Food: 10, Tech: 35, Manpower: 3}, Latitude: 23.59, Longitude: 58.38, CapitalName: "Muscat", Population: 5100000, TerrainTheme: "desert", Adjacency: []string{"SAU", "ARE", "YEM"}},
	{ISO3: "BHR", Name: "Bahrain", Continent: "Asia", Tier: TierC, Resources: Resources{Oil: 50, Minerals: 5, Food: 5, Tech: 45, Manpower: 1}, Latitude: 26.07, Longitude: 50.56, CapitalName: "Manama", Population: 1700000, TerrainTheme: "island", Adjacency: []string{"SAU", "QAT"}},
	{ISO3: "ECU", Name: "Ecuador", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 50, Minerals: 30, Food: 55, Tech: 25, Manpower: 12}, Latitude: -0.18, Longitude: -78.47, CapitalName: "Quito", Population: 17600000, TerrainTheme: "mountain", Adjacency: []string{"COL", "PER"}},
	{ISO3: "BOL", Name: "Bolivia", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 20, Minerals: 55, Food: 40, Tech: 15, Manpower: 8}, Latitude: -16.50, Longitude: -68.15, CapitalName: "La Paz", Population: 11700000, TerrainTheme: "mountain", Adjacency: []string{"BRA", "PRY", "ARG", "CHL", "PER"}},
	{ISO3: "PRY", Name: "Paraguay", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 15, Food: 60, Tech: 15, Manpower: 5}, Latitude: -25.26, Longitude: -57.58, CapitalName: "Asuncion", Population: 7100000, TerrainTheme: "plains", Adjacency: []string{"BRA", "ARG", "BOL"}},
	{ISO3: "URY", Name: "Uruguay", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 10, Food: 65, Tech: 40, Manpower: 3}, Latitude: -34.90, Longitude: -56.16, CapitalName: "Montevideo", Population: 3500000, TerrainTheme: "plains", Adjacency: []string{"BRA", "ARG"}},
	{ISO3: "GUY", Name: "Guyana", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 55, Minerals: 40, Food: 35, Tech: 10, Manpower: 1}, Latitude: 6.80, Longitude: -58.16, CapitalName: "Georgetown", Population: 786000, TerrainTheme: "forest", Adjacency: []string{"VEN", "BRA", "SUR"}},
	{ISO3: "SUR", Name: "Suriname", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 20, Minerals: 40, Food: 25, Tech: 10, Manpower: 1}, Latitude: 5.85, Longitude: -55.20, CapitalName: "Paramaribo", Population: 587000, TerrainTheme: "forest", Adjacency: []string{"GUY", "BRA", "GUF"}},
	{ISO3: "PAN", Name: "Panama", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 10, Food: 30, Tech: 35, Manpower: 3}, Latitude: 8.98, Longitude: -79.52, CapitalName: "Panama City", Population: 4300000, TerrainTheme: "forest", Adjacency: []string{"COL", "CRI"}},
	{ISO3: "CRI", Name: "Costa Rica", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 10, Food: 45, Tech: 40, Manpower: 4}, Latitude: 9.93, Longitude: -84.08, CapitalName: "San Jose", Population: 5100000, TerrainTheme: "forest", Adjacency: []string{"NIC", "PAN"}},
	{ISO3: "GTM", Name: "Guatemala", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 15, Food: 40, Tech: 15, Manpower: 12}, Latitude: 14.63, Longitude: -90.51, CapitalName: "Guatemala City", Population: 17900000, TerrainTheme: "forest", Adjacency: []string{"MEX", "BLZ", "HND", "SLV"}},
	{ISO3: "HND", Name: "Honduras", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 15, Food: 35, Tech: 10, Manpower: 7}, Latitude: 14.07, Longitude: -87.22, CapitalName: "Tegucigalpa", Population: 9900000, TerrainTheme: "forest", Adjacency: []string{"GTM", "SLV", "NIC"}},
	{ISO3: "SLV", Name: "El Salvador", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 10, Food: 35, Tech: 15, Manpower: 5}, Latitude: 13.69, Longitude: -89.19, CapitalName: "San Salvador", Population: 6500000, TerrainTheme: "mountain", Adjacency: []string{"GTM", "HND"}},
	{ISO3: "NIC", Name: "Nicaragua", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 15, Food: 35, Tech: 10, Manpower: 5}, Latitude: 12.15, Longitude: -86.27, CapitalName: "Managua", Population: 6600000, TerrainTheme: "forest", Adjacency: []string{"HND", "CRI"}},
	{ISO3: "DOM", Name: "Dominican Republic", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 20, Food: 40, Tech: 20, Manpower: 8}, Latitude: 18.47, Longitude: -69.90, CapitalName: "Santo Domingo", Population: 10800000, TerrainTheme: "island", Adjacency: []string{"HTI"}},
	{ISO3: "HTI", Name: "Haiti", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 10, Food: 25, Tech: 5, Manpower: 8}, Latitude: 18.54, Longitude: -72.34, CapitalName: "Port-au-Prince", Population: 11400000, TerrainTheme: "island", Adjacency: []string{"DOM", "CUB"}},
	{ISO3: "JAM", Name: "Jamaica", Continent: "North America", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 25, Food: 30, Tech: 20, Manpower: 2}, Latitude: 18.00, Longitude: -76.79, CapitalName: "Kingston", Population: 3000000, TerrainTheme: "island", Adjacency: []string{"CUB"}},
	{ISO3: "TTO", Name: "Trinidad and Tobago", Continent: "South America", Tier: TierC, Resources: Resources{Oil: 50, Minerals: 10, Food: 15, Tech: 30, Manpower: 1}, Latitude: 10.65, Longitude: -61.50, CapitalName: "Port of Spain", Population: 1400000, TerrainTheme: "island", Adjacency: []string{"VEN"}},
	{ISO3: "SDN", Name: "Sudan", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 40, Minerals: 25, Food: 35, Tech: 10, Manpower: 25}, Latitude: 15.60, Longitude: 32.53, CapitalName: "Khartoum", Population: 43800000, TerrainTheme: "desert", Adjacency: []string{"EGY", "LBY", "TCD", "CAF", "SSD", "ETH", "ERI"}},
	{ISO3: "TZA", Name: "Tanzania", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 10, Minerals: 40, Food: 50, Tech: 15, Manpower: 35}, Latitude: -6.16, Longitude: 35.74, CapitalName: "Dodoma", Population: 59700000, TerrainTheme: "plains", Adjacency: []string{"KEN", "UGA", "RWA", "BDI", "COD", "ZMB", "MWI", "MOZ"}},
	{ISO3: "GHA", Name: "Ghana", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 30, Minerals: 35, Food: 45, Tech: 20, Manpower: 18}, Latitude: 5.55, Longitude: -0.20, CapitalName: "Accra", Population: 31100000, TerrainTheme: "forest", Adjacency: []string{"CIV", "BFA", "TGO"}},
	{ISO3: "CIV", Name: "Ivory Coast", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 20, Food: 55, Tech: 15, Manpower: 16}, Latitude: 6.83, Longitude: -5.29, CapitalName: "Yamoussoukro", Population: 26400000, TerrainTheme: "forest", Adjacency: []string{"LBR", "GIN", "MLI", "BFA", "GHA"}},
	{ISO3: "CMR", Name: "Cameroon", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 30, Minerals: 25, Food: 45, Tech: 15, Manpower: 16}, Latitude: 3.87, Longitude: 11.52, CapitalName: "Yaounde", Population: 26500000, TerrainTheme: "forest", Adjacency: []string{"NGA", "TCD", "CAF", "COG", "GAB", "GNQ"}},
	{ISO3: "TUN", Name: "Tunisia", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 25, Minerals: 25, Food: 35, Tech: 30, Manpower: 8}, Latitude: 36.81, Longitude: 10.18, CapitalName: "Tunis", Population: 11800000, TerrainTheme: "desert", Adjacency: []string{"DZA", "LBY"}},
	{ISO3: "UGA", Name: "Uganda", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 25, Food: 50, Tech: 15, Manpower: 25}, Latitude: 0.35, Longitude: 32.58, CapitalName: "Kampala", Population: 45700000, TerrainTheme: "plains", Adjacency: []string{"KEN", "TZA", "RWA", "COD", "SSD"}},
	{ISO3: "SEN", Name: "Senegal", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 25, Food: 40, Tech: 20, Manpower: 10}, Latitude: 14.69, Longitude: -17.44, CapitalName: "Dakar", Population: 16700000, TerrainTheme: "plains", Adjacency: []string{"MRT", "MLI", "GIN", "GNB", "GMB"}},
	{ISO3: "ZMB", Name: "Zambia", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 70, Food: 40, Tech: 10, Manpower: 12}, Latitude: -15.39, Longitude: 28.32, CapitalName: "Lusaka", Population: 18400000, TerrainTheme: "plains", Adjacency: []string{"COD", "TZA", "MWI", "MOZ", "ZWE", "BWA", "NAM", "AGO"}},
	{ISO3: "ZWE", Name: "Zimbabwe", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 55, Food: 35, Tech: 15, Manpower: 10}, Latitude: -17.83, Longitude: 31.05, CapitalName: "Harare", Population: 14900000, TerrainTheme: "plains", Adjacency: []string{"ZAF", "BWA", "ZMB", "MOZ"}},
	{ISO3: "MOZ", Name: "Mozambique", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 30, Food: 40, Tech: 10, Manpower: 18}, Latitude: -25.97, Longitude: 32.58, CapitalName: "Maputo", Population: 31300000, TerrainTheme: "plains", Adjacency: []string{"ZAF", "SWZ", "ZWE", "ZMB", "MWI", "TZA"}},
	{ISO3: "MDG", Name: "Madagascar", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 30, Food: 45, Tech: 10, Manpower: 18}, Latitude: -18.88, Longitude: 47.51, CapitalName: "Antananarivo", Population: 27700000, TerrainTheme: "island", Adjacency: []string{"MOZ"}},
	{ISO3: "MDA", Name: "Moldova", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 10, Food: 50, Tech: 25, Manpower: 3}, Latitude: 47.01, Longitude: 28.86, CapitalName: "Chisinau", Population: 2600000, TerrainTheme: "plains", Adjacency: []string{"UKR", "ROU"}},
	{ISO3: "ALB", Name: "Albania", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 20, Food: 35, Tech: 25, Manpower: 3}, Latitude: 41.33, Longitude: 19.82, CapitalName: "Tirana", Population: 2900000, TerrainTheme: "mountain", Adjacency: []string{"MNE", "XKX", "MKD", "GRC"}},
	{ISO3: "MKD", Name: "North Macedonia", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 20, Food: 35, Tech: 25, Manpower: 2}, Latitude: 42.00, Longitude: 21.43, CapitalName: "Skopje", Population: 2100000, TerrainTheme: "mountain", Adjacency: []string{"SRB", "BGR", "GRC", "ALB", "XKX"}},
	{ISO3: "MNE", Name: "Montenegro", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 15, Food: 30, Tech: 30, Manpower: 1}, Latitude: 42.44, Longitude: 19.26, CapitalName: "Podgorica", Population: 620000, TerrainTheme: "mountain", Adjacency: []string{"HRV", "BIH", "SRB", "XKX", "ALB"}},
	{ISO3: "BIH", Name: "Bosnia and Herzegovina", Continent: "Europe", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 20, Food: 35, Tech: 25, Manpower: 3}, Latitude: 43.86, Longitude: 18.41, CapitalName: "Sarajevo", Population: 3300000, TerrainTheme: "mountain", Adjacency: []string{"HRV", "SRB", "MNE"}},
	{ISO3: "TCD", Name: "Chad", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 40, Minerals: 20, Food: 25, Tech: 5, Manpower: 10}, Latitude: 12.13, Longitude: 15.06, CapitalName: "N'Djamena", Population: 16400000, TerrainTheme: "desert", Adjacency: []string{"LBY", "NER", "NGA", "CMR", "CAF", "SDN"}},
	{ISO3: "NER", Name: "Niger", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 40, Food: 25, Tech: 5, Manpower: 15}, Latitude: 13.51, Longitude: 2.11, CapitalName: "Niamey", Population: 24200000, TerrainTheme: "desert", Adjacency: []string{"DZA", "LBY", "TCD", "NGA", "BEN", "BFA", "MLI"}},
	{ISO3: "MLI", Name: "Mali", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 35, Food: 30, Tech: 5, Manpower: 12}, Latitude: 12.65, Longitude: -8.00, CapitalName: "Bamako", Population: 20300000, TerrainTheme: "desert", Adjacency: []string{"DZA", "NER", "BFA", "CIV", "GIN", "SEN", "MRT"}},
	{ISO3: "BFA", Name: "Burkina Faso", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 0, Minerals: 30, Food: 35, Tech: 5, Manpower: 12}, Latitude: 12.37, Longitude: -1.52, CapitalName: "Ouagadougou", Population: 20900000, TerrainTheme: "plains", Adjacency: []string{"MLI", "NER", "BEN", "TGO", "GHA", "CIV"}},
	{ISO3: "SOM", Name: "Somalia", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 15, Minerals: 15, Food: 20, Tech: 5, Manpower: 10}, Latitude: 2.05, Longitude: 45.32, CapitalName: "Mogadishu", Population: 15900000, TerrainTheme: "desert", Adjacency: []string{"ETH", "KEN", "DJI"}},
	{ISO3: "CAF", Name: "Central African Republic", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 5, Minerals: 40, Food: 30, Tech: 5, Manpower: 4}, Latitude: 4.37, Longitude: 18.58, CapitalName: "Bangui", Population: 4800000, TerrainTheme: "forest", Adjacency: []string{"CMR", "TCD", "SDN", "SSD", "COD", "COG"}},
	{ISO3: "SSD", Name: "South Sudan", Continent: "Africa", Tier: TierC, Resources: Resources{Oil: 50, Minerals: 15, Food: 25, Tech: 5, Manpower: 8}, Latitude: 4.85, Longitude: 31.60, CapitalName: "Juba", Population: 11200000, TerrainTheme: "plains", Adjacency: []string{"SDN", "ETH", "KEN", "UGA", "COD", "CAF"}},

	// ============================================================
	// D-TIER: Minor (47) — smaller/island nations
	// ============================================================
	{ISO3: "ISL", Name: "Iceland", Continent: "Europe", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 5, Food: 25, Tech: 70, Manpower: 0}, Latitude: 64.15, Longitude: -21.94, CapitalName: "Reykjavik", Population: 364000, TerrainTheme: "arctic", Adjacency: []string{"GBR", "NOR"}},
	{ISO3: "LUX", Name: "Luxembourg", Continent: "Europe", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 10, Food: 20, Tech: 65, Manpower: 1}, Latitude: 49.61, Longitude: 6.13, CapitalName: "Luxembourg", Population: 634000, TerrainTheme: "plains", Adjacency: []string{"DEU", "FRA", "BEL"}},
	{ISO3: "MLT", Name: "Malta", Continent: "Europe", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 5, Food: 15, Tech: 45, Manpower: 0}, Latitude: 35.90, Longitude: 14.51, CapitalName: "Valletta", Population: 514000, TerrainTheme: "island", Adjacency: []string{"ITA"}},
	{ISO3: "CYP", Name: "Cyprus", Continent: "Europe", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 10, Food: 25, Tech: 45, Manpower: 1}, Latitude: 35.17, Longitude: 33.36, CapitalName: "Nicosia", Population: 1200000, TerrainTheme: "island", Adjacency: []string{"TUR", "GRC"}},
	{ISO3: "BRN", Name: "Brunei", Continent: "Asia", Tier: TierD, Resources: Resources{Oil: 70, Minerals: 5, Food: 10, Tech: 35, Manpower: 0}, Latitude: 4.94, Longitude: 114.95, CapitalName: "Bandar Seri Begawan", Population: 437000, TerrainTheme: "forest", Adjacency: []string{"MYS"}},
	{ISO3: "BTN", Name: "Bhutan", Continent: "Asia", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 10, Food: 30, Tech: 10, Manpower: 1}, Latitude: 27.47, Longitude: 89.64, CapitalName: "Thimphu", Population: 771000, TerrainTheme: "mountain", Adjacency: []string{"IND", "CHN"}},
	{ISO3: "TLS", Name: "Timor-Leste", Continent: "Asia", Tier: TierD, Resources: Resources{Oil: 40, Minerals: 5, Food: 25, Tech: 5, Manpower: 1}, Latitude: -8.56, Longitude: 125.57, CapitalName: "Dili", Population: 1300000, TerrainTheme: "island", Adjacency: []string{"IDN"}},
	{ISO3: "MDV", Name: "Maldives", Continent: "Asia", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 0, Food: 15, Tech: 20, Manpower: 0}, Latitude: 4.18, Longitude: 73.51, CapitalName: "Male", Population: 541000, TerrainTheme: "island", Adjacency: []string{"LKA", "IND"}},
	{ISO3: "FJI", Name: "Fiji", Continent: "Oceania", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 15, Food: 35, Tech: 15, Manpower: 1}, Latitude: -18.14, Longitude: 178.44, CapitalName: "Suva", Population: 896000, TerrainTheme: "island", Adjacency: []string{"NZL"}},
	{ISO3: "PNG", Name: "Papua New Guinea", Continent: "Oceania", Tier: TierD, Resources: Resources{Oil: 20, Minerals: 50, Food: 40, Tech: 5, Manpower: 6}, Latitude: -6.21, Longitude: 155.97, CapitalName: "Port Moresby", Population: 8900000, TerrainTheme: "forest", Adjacency: []string{"IDN", "AUS"}},
	{ISO3: "BLZ", Name: "Belize", Continent: "North America", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 5, Food: 30, Tech: 10, Manpower: 0}, Latitude: 17.25, Longitude: -88.77, CapitalName: "Belmopan", Population: 398000, TerrainTheme: "forest", Adjacency: []string{"MEX", "GTM"}},
	{ISO3: "BHS", Name: "Bahamas", Continent: "North America", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 5, Food: 15, Tech: 25, Manpower: 0}, Latitude: 25.05, Longitude: -77.35, CapitalName: "Nassau", Population: 393000, TerrainTheme: "island", Adjacency: []string{"USA", "CUB"}},
	{ISO3: "GNQ", Name: "Equatorial Guinea", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 60, Minerals: 10, Food: 20, Tech: 10, Manpower: 1}, Latitude: 3.75, Longitude: 8.78, CapitalName: "Malabo", Population: 1400000, TerrainTheme: "forest", Adjacency: []string{"CMR", "GAB"}},
	{ISO3: "GAB", Name: "Gabon", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 55, Minerals: 35, Food: 25, Tech: 15, Manpower: 1}, Latitude: 0.39, Longitude: 9.45, CapitalName: "Libreville", Population: 2200000, TerrainTheme: "forest", Adjacency: []string{"CMR", "GNQ", "COG"}},
	{ISO3: "COG", Name: "Republic of Congo", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 55, Minerals: 25, Food: 30, Tech: 10, Manpower: 4}, Latitude: -4.27, Longitude: 15.28, CapitalName: "Brazzaville", Population: 5500000, TerrainTheme: "forest", Adjacency: []string{"GAB", "CMR", "CAF", "COD", "AGO"}},
	{ISO3: "NAM", Name: "Namibia", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 55, Food: 20, Tech: 15, Manpower: 2}, Latitude: -22.57, Longitude: 17.08, CapitalName: "Windhoek", Population: 2500000, TerrainTheme: "desert", Adjacency: []string{"AGO", "ZMB", "BWA", "ZAF"}},
	{ISO3: "BWA", Name: "Botswana", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 65, Food: 20, Tech: 20, Manpower: 2}, Latitude: -24.65, Longitude: 25.91, CapitalName: "Gaborone", Population: 2400000, TerrainTheme: "desert", Adjacency: []string{"ZAF", "NAM", "ZWE", "ZMB"}},
	{ISO3: "SWZ", Name: "Eswatini", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 15, Food: 30, Tech: 10, Manpower: 1}, Latitude: -26.31, Longitude: 31.13, CapitalName: "Mbabane", Population: 1200000, TerrainTheme: "plains", Adjacency: []string{"ZAF", "MOZ"}},
	{ISO3: "LSO", Name: "Lesotho", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 15, Food: 25, Tech: 5, Manpower: 2}, Latitude: -29.31, Longitude: 27.48, CapitalName: "Maseru", Population: 2100000, TerrainTheme: "mountain", Adjacency: []string{"ZAF"}},
	{ISO3: "MWI", Name: "Malawi", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 15, Food: 40, Tech: 5, Manpower: 12}, Latitude: -13.97, Longitude: 33.79, CapitalName: "Lilongwe", Population: 19100000, TerrainTheme: "plains", Adjacency: []string{"TZA", "MOZ", "ZMB"}},
	{ISO3: "RWA", Name: "Rwanda", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 25, Food: 35, Tech: 20, Manpower: 8}, Latitude: -1.94, Longitude: 29.87, CapitalName: "Kigali", Population: 12900000, TerrainTheme: "mountain", Adjacency: []string{"UGA", "TZA", "BDI", "COD"}},
	{ISO3: "BDI", Name: "Burundi", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 15, Food: 30, Tech: 5, Manpower: 7}, Latitude: -3.38, Longitude: 29.36, CapitalName: "Gitega", Population: 11900000, TerrainTheme: "mountain", Adjacency: []string{"RWA", "TZA", "COD"}},
	{ISO3: "ERI", Name: "Eritrea", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 25, Food: 15, Tech: 5, Manpower: 3}, Latitude: 15.34, Longitude: 38.93, CapitalName: "Asmara", Population: 3500000, TerrainTheme: "desert", Adjacency: []string{"SDN", "ETH", "DJI"}},
	{ISO3: "DJI", Name: "Djibouti", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 5, Food: 10, Tech: 10, Manpower: 1}, Latitude: 11.59, Longitude: 43.15, CapitalName: "Djibouti", Population: 988000, TerrainTheme: "desert", Adjacency: []string{"ERI", "ETH", "SOM"}},
	{ISO3: "LBR", Name: "Liberia", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 30, Food: 30, Tech: 5, Manpower: 4}, Latitude: 6.31, Longitude: -10.80, CapitalName: "Monrovia", Population: 5100000, TerrainTheme: "forest", Adjacency: []string{"SLE", "GIN", "CIV"}},
	{ISO3: "SLE", Name: "Sierra Leone", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 35, Food: 30, Tech: 5, Manpower: 5}, Latitude: 8.49, Longitude: -13.23, CapitalName: "Freetown", Population: 8000000, TerrainTheme: "forest", Adjacency: []string{"GIN", "LBR"}},
	{ISO3: "GIN", Name: "Guinea", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 55, Food: 35, Tech: 5, Manpower: 8}, Latitude: 9.64, Longitude: -13.58, CapitalName: "Conakry", Population: 13100000, TerrainTheme: "forest", Adjacency: []string{"SEN", "MLI", "CIV", "LBR", "SLE", "GNB"}},
	{ISO3: "GNB", Name: "Guinea-Bissau", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 10, Food: 25, Tech: 5, Manpower: 1}, Latitude: 11.86, Longitude: -15.60, CapitalName: "Bissau", Population: 2000000, TerrainTheme: "forest", Adjacency: []string{"SEN", "GIN"}},
	{ISO3: "GMB", Name: "Gambia", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 5, Food: 25, Tech: 5, Manpower: 2}, Latitude: 13.45, Longitude: -16.58, CapitalName: "Banjul", Population: 2400000, TerrainTheme: "plains", Adjacency: []string{"SEN"}},
	{ISO3: "MRT", Name: "Mauritania", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 15, Minerals: 40, Food: 15, Tech: 5, Manpower: 3}, Latitude: 18.09, Longitude: -15.98, CapitalName: "Nouakchott", Population: 4600000, TerrainTheme: "desert", Adjacency: []string{"MAR", "DZA", "MLI", "SEN"}},
	{ISO3: "TGO", Name: "Togo", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 25, Food: 35, Tech: 5, Manpower: 5}, Latitude: 6.17, Longitude: 1.23, CapitalName: "Lome", Population: 8300000, TerrainTheme: "plains", Adjacency: []string{"GHA", "BFA", "BEN"}},
	{ISO3: "BEN", Name: "Benin", Continent: "Africa", Tier: TierD, Resources: Resources{Oil: 10, Minerals: 10, Food: 40, Tech: 10, Manpower: 8}, Latitude: 6.37, Longitude: 2.43, CapitalName: "Porto-Novo", Population: 12100000, TerrainTheme: "plains", Adjacency: []string{"TGO", "BFA", "NER", "NGA"}},
	{ISO3: "PSE", Name: "Palestine", Continent: "Asia", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 5, Food: 15, Tech: 15, Manpower: 3}, Latitude: 31.95, Longitude: 35.20, CapitalName: "Ramallah", Population: 5100000, TerrainTheme: "desert", Adjacency: []string{"ISR", "EGY", "JOR"}},
	{ISO3: "XKX", Name: "Kosovo", Continent: "Europe", Tier: TierD, Resources: Resources{Oil: 0, Minerals: 25, Food: 25, Tech: 15, Manpower: 2}, Latitude: 42.66, Longitude: 21.17, CapitalName: "Pristina", Population: 1800000, TerrainTheme: "mountain", Adjacency: []string{"SRB", "MNE", "ALB", "MKD"}},
	{ISO3: "GUF", Name: "French Guiana", Continent: "South America", Tier: TierD, Resources: Resources{Oil: 5, Minerals: 15, Food: 20, Tech: 25, Manpower: 0}, Latitude: 4.92, Longitude: -52.31, CapitalName: "Cayenne", Population: 299000, TerrainTheme: "forest", Adjacency: []string{"BRA", "SUR"}},
}

// CountryCount returns the total number of seeded countries.
func CountryCount() int {
	return len(AllCountries)
}

// GetCountryByISO3 looks up a country by its ISO3 code.
func GetCountryByISO3(iso3 string) *CountrySeed {
	for i := range AllCountries {
		if AllCountries[i].ISO3 == iso3 {
			return &AllCountries[i]
		}
	}
	return nil
}

// GetCountriesByTier returns all countries of a given tier.
func GetCountriesByTier(tier CountryTier) []CountrySeed {
	var result []CountrySeed
	for _, c := range AllCountries {
		if c.Tier == tier {
			result = append(result, c)
		}
	}
	return result
}

// GetCountriesByContinent returns all countries in a continent.
func GetCountriesByContinent(continent string) []CountrySeed {
	var result []CountrySeed
	for _, c := range AllCountries {
		if c.Continent == continent {
			result = append(result, c)
		}
	}
	return result
}

