/**
 * definitions.ts - AI World War Skill Definitions
 * 55 Skills organized by Category (STEEL/TERRITORY/ALLIANCE/SOVEREIGNTY/INTELLIGENCE/MORALE)
 */

import { type SkillDefinition, type SkillCategory, type WeaponType } from '../../types';
export type { SkillDefinition, SkillCategory };

// ============================================
// STEEL (강철) Category Skills (10 skills) — CODE
// ============================================

export const CODE_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'knife' as WeaponType,
    name: '철의 세례',
    nameEn: 'Iron Baptism',
    description: '공장에서 막 찍어낸 총탄의 세례. 기본이지만 확실한 투사체',
    descriptionEn: 'Fast-forged bullets from the factory. Basic but reliable projectile',
    category: 'CODE',
    tier: 'basic',
    icon: 'Crosshair',
    color: '#EF4444',
    synergyTags: ['projectile', 'fast', 'basic'],
    recommendedWith: ['bow', 'shard'],
  },
  {
    id: 'whip' as WeaponType,
    name: '강철 채찍',
    nameEn: 'Steel Lash',
    description: '용광로에서 달군 강철 채찍. 넓은 범위를 휩쓴다',
    descriptionEn: 'Red-hot steel lash from the furnace. Sweeps a wide area',
    category: 'CODE',
    tier: 'basic',
    icon: 'Sword',
    color: '#EF4444',
    synergyTags: ['melee', 'sweep', 'basic'],
    recommendedWith: ['punch', 'sword'],
  },
  {
    id: 'wand' as WeaponType,
    name: '추적탄',
    nameEn: 'Tracer Round',
    description: '국가 기술력으로 만든 자동 추적탄. 알아서 찾아간다',
    descriptionEn: 'State-engineered tracer rounds. Auto-aim homing projectile',
    category: 'CODE',
    tier: 'basic',
    icon: 'Rocket',
    color: '#EF4444',
    synergyTags: ['magic', 'homing', 'basic'],
    recommendedWith: ['lightning', 'beam'],
  },
  {
    id: 'axe' as WeaponType,
    name: '전차포',
    nameEn: 'Tank Shell',
    description: '중공업의 정수. 무겁지만 뚫지 못할 것은 없다',
    descriptionEn: 'Pinnacle of heavy industry. Heavy but unstoppable pierce',
    category: 'CODE',
    tier: 'advanced',
    icon: 'Bomb',
    color: '#EF4444',
    synergyTags: ['projectile', 'heavy', 'pierce'],
    recommendedWith: ['fork', 'airdrop'],
  },
  {
    id: 'bow' as WeaponType,
    name: '텅스텐 관통탄',
    nameEn: 'Tungsten Penetrator',
    description: '희귀 금속으로 제작한 극초음속 관통탄',
    descriptionEn: 'Hypersonic round crafted from rare tungsten. High pierce',
    category: 'CODE',
    tier: 'advanced',
    icon: 'Target',
    color: '#EF4444',
    synergyTags: ['projectile', 'pierce', 'precise'],
    recommendedWith: ['knife', 'shard'],
  },
  // === New Skills ===
  {
    id: 'syntax_error' as WeaponType,
    name: 'EMP 수류탄',
    nameEn: 'EMP Grenade',
    description: '적 장비를 무력화시키는 전자기 펄스. 연쇄 스턴',
    descriptionEn: 'Electromagnetic pulse disabling enemy equipment. Chain stun',
    category: 'CODE',
    tier: 'advanced',
    icon: 'Zap',
    color: '#FF6B6B',
    synergyTags: ['debuff', 'stun', 'spread'],
    recommendedWith: ['debugger_skill', 'compiler'],
  },
  {
    id: 'compiler' as WeaponType,
    name: '궤도포',
    nameEn: 'Orbital Cannon',
    description: '위성 궤도에서 발사하는 에너지 빔. 충전 필요하지만 파괴적',
    descriptionEn: 'Energy beam from orbital satellite. Requires charge but devastating',
    category: 'CODE',
    tier: 'advanced',
    icon: 'Zap',
    color: '#EF4444',
    synergyTags: ['beam', 'charge', 'powerful'],
    recommendedWith: ['beam', 'laser'],
  },
  {
    id: 'debugger_skill' as WeaponType,
    name: '아킬레스',
    nameEn: 'Achilles Protocol',
    description: '적의 구조적 약점을 분석하여 일격에 쓰러뜨리는 프로토콜',
    descriptionEn: 'Analyze structural weak points for instant kill chance. Bonus vs bosses',
    category: 'CODE',
    tier: 'elite',
    icon: 'Crosshair',
    color: '#F59E0B',
    synergyTags: ['execute', 'boss_killer', 'utility'],
    recommendedWith: ['syntax_error', 'hotfix'],
  },
  {
    id: 'refactor' as WeaponType,
    name: '군수 개혁',
    nameEn: 'Arms Reform',
    description: '무기 체계를 재정비. 전군의 사격 속도가 빨라진다',
    descriptionEn: 'Overhaul the arms system. Reduces all skill cooldowns',
    category: 'CODE',
    tier: 'elite',
    icon: 'RadioTower',
    color: '#10B981',
    synergyTags: ['buff', 'cooldown', 'utility'],
    recommendedWith: ['overclock', 'cache'],
  },
  {
    id: 'hotfix' as WeaponType,
    name: '야전 수리',
    nameEn: 'Field Repair',
    description: '산업력으로 전장에서도 즉석 수리. 위기일수록 빠르게',
    descriptionEn: 'Field repair powered by industry. Stronger in critical situations',
    category: 'CODE',
    tier: 'elite',
    icon: 'Heart',
    color: '#EF4444',
    synergyTags: ['heal', 'emergency', 'survival'],
    recommendedWith: ['antivirus', 'firewall_surge'],
  },
];

// ============================================
// TERRITORY (영토) Category Skills (10 skills) — DATA
// ============================================

export const DATA_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'bible' as WeaponType,
    name: '국경 순찰',
    nameEn: 'Border Patrol',
    description: '영토 주변을 순찰하는 방위 체계. 접근하는 적에게 지속 피해',
    descriptionEn: 'Border defense patrol orbiting territory. Sustained damage to approaching enemies',
    category: 'DATA',
    tier: 'basic',
    icon: 'BookOpen',
    color: '#3B82F6',
    synergyTags: ['orbit', 'sustained', 'basic'],
    recommendedWith: ['garlic', 'pool'],
  },
  {
    id: 'pool' as WeaponType,
    name: '소각 지대',
    nameEn: 'Scorched Earth',
    description: '초토화 작전. 발밑의 땅을 불태워 적에게 지속 피해',
    descriptionEn: 'Scorched earth tactic. Burns the ground below for sustained area damage',
    category: 'DATA',
    tier: 'basic',
    icon: 'Flame',
    color: '#F97316',
    synergyTags: ['aoe', 'zone', 'sustained'],
    recommendedWith: ['bible', 'garlic'],
  },
  {
    id: 'shard' as WeaponType,
    name: '파편 폭풍',
    nameEn: 'Shrapnel Storm',
    description: '포탄 파편이 사방으로 흩어져 다수를 동시 공격',
    descriptionEn: 'Shell fragments scatter in all directions to hit multiple enemies',
    category: 'DATA',
    tier: 'advanced',
    icon: 'Sparkles',
    color: '#3B82F6',
    synergyTags: ['projectile', 'multi', 'scatter'],
    recommendedWith: ['knife', 'fork'],
  },
  {
    id: 'airdrop' as WeaponType,
    name: '카펫 바밍',
    nameEn: 'Carpet Bombing',
    description: '하늘에서 융단 폭격. 넓은 영토를 초토화',
    descriptionEn: 'Carpet bombing from the sky. Wide area devastation',
    category: 'DATA',
    tier: 'advanced',
    icon: 'Plane',
    color: '#3B82F6',
    synergyTags: ['aoe', 'explosion', 'ranged'],
    recommendedWith: ['pool', 'tcp_flood'],
  },
  // === New Skills ===
  {
    id: 'json_bomb' as WeaponType,
    name: '집속탄',
    nameEn: 'Cluster Munition',
    description: '하나의 탄두가 수십 개 자탄으로 분열. 연쇄 폭발',
    descriptionEn: 'Single warhead splits into dozens of submunitions. Chain explosion',
    category: 'DATA',
    tier: 'basic',
    icon: 'Braces',
    color: '#F59E0B',
    synergyTags: ['aoe', 'chain', 'explosion'],
    recommendedWith: ['csv_spray', 'sql_injection'],
  },
  {
    id: 'csv_spray' as WeaponType,
    name: '기관총 진지',
    nameEn: 'MG Nest',
    description: '고지를 점령한 기관총 진지에서 쏟아지는 탄막',
    descriptionEn: 'Hail of bullets from an elevated MG nest. High fire rate',
    category: 'DATA',
    tier: 'basic',
    icon: 'Table',
    color: '#3B82F6',
    synergyTags: ['projectile', 'rapid', 'multi'],
    recommendedWith: ['json_bomb', 'knife'],
  },
  {
    id: 'sql_injection' as WeaponType,
    name: '지하 침투',
    nameEn: 'Underground Breach',
    description: '땅 아래로 침투하여 적 방어선을 무시. 장갑 무효화',
    descriptionEn: 'Tunnel beneath to bypass enemy defenses. Ignores armor',
    category: 'DATA',
    tier: 'advanced',
    icon: 'Database',
    color: '#EF4444',
    synergyTags: ['debuff', 'pierce', 'boss_killer'],
    recommendedWith: ['debugger_skill', 'encryption'],
  },
  {
    id: 'regex' as WeaponType,
    name: '지형 이점',
    nameEn: 'Terrain Advantage',
    description: '영토의 지형을 이용. 특정 유형의 적에게 추가 데미지',
    descriptionEn: 'Exploit terrain for bonus damage against specific enemy types',
    category: 'DATA',
    tier: 'advanced',
    icon: 'Search',
    color: '#8B5CF6',
    synergyTags: ['precise', 'conditional', 'utility'],
    recommendedWith: ['neural_net', 'debugger_skill'],
  },
  {
    id: 'binary' as WeaponType,
    name: '지각 변동',
    nameEn: 'Tectonic Shift',
    description: '대지의 충격파로 적을 밀어내며 짓밟는다',
    descriptionEn: 'Seismic shockwave pushes and crushes enemies',
    category: 'DATA',
    tier: 'elite',
    icon: 'Binary',
    color: '#3B82F6',
    synergyTags: ['wave', 'knockback', 'sustained'],
    recommendedWith: ['beam', 'laser'],
  },
  {
    id: 'big_data' as WeaponType,
    name: '총력 동원',
    nameEn: 'Total Mobilization',
    description: '영토의 모든 자원을 전쟁에 투입. 전과에 비례해 폭발적',
    descriptionEn: 'Pour all territorial resources into war. Scales with kill count',
    category: 'DATA',
    tier: 'elite',
    icon: 'BarChart3',
    color: '#3B82F6',
    synergyTags: ['scaling', 'aoe', 'powerful'],
    recommendedWith: ['json_bomb', 'airdrop'],
  },
];

// ============================================
// ALLIANCE (동맹) Category Skills (10 skills) — NETWORK
// ============================================

export const NETWORK_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'bridge' as WeaponType,
    name: '연합 공격',
    nameEn: 'Coalition Strike',
    description: '동맹국과 함께 적을 포위. 데미지가 체인으로 공유',
    descriptionEn: 'Surround enemies with coalition allies. Chain damage sharing',
    category: 'NETWORK',
    tier: 'basic',
    icon: 'Link',
    color: '#8B5CF6',
    synergyTags: ['chain', 'multi', 'basic'],
    recommendedWith: ['ping', 'websocket'],
  },
  {
    id: 'ping' as WeaponType,
    name: '외교 전서',
    nameEn: 'Diplomatic Cable',
    description: '빠른 외교 채널로 즉각 반응. 적을 탐지하고 타격',
    descriptionEn: 'Swift diplomatic channels detect and strike enemies',
    category: 'NETWORK',
    tier: 'basic',
    icon: 'Radio',
    color: '#8B5CF6',
    synergyTags: ['fast', 'homing', 'basic'],
    recommendedWith: ['bridge', 'knife'],
  },
  {
    id: 'fork' as WeaponType,
    name: '연합 분산 공격',
    nameEn: 'Allied Divergence',
    description: '동맹군이 분산하여 여러 적 동시 타격',
    descriptionEn: 'Allied forces diverge to strike multiple enemies simultaneously',
    category: 'NETWORK',
    tier: 'advanced',
    icon: 'GitFork',
    color: '#8B5CF6',
    synergyTags: ['split', 'multi', 'projectile'],
    recommendedWith: ['shard', 'knife'],
  },
  // === New Skills ===
  {
    id: 'websocket' as WeaponType,
    name: '영구 동맹',
    nameEn: 'Permanent Alliance',
    description: '끊기지 않는 동맹의 연결. 지속할수록 강력해진다',
    descriptionEn: 'Unbreakable alliance bond. Grows stronger over time',
    category: 'NETWORK',
    tier: 'basic',
    icon: 'Plug',
    color: '#8B5CF6',
    synergyTags: ['beam', 'sustained', 'scaling'],
    recommendedWith: ['bridge', 'beam'],
  },
  {
    id: 'tcp_flood' as WeaponType,
    name: '경제 제재',
    nameEn: 'Economic Sanction',
    description: '국제 제재로 적의 경제를 마비. 슬로우 효과',
    descriptionEn: 'International sanctions cripple enemy economy. Slows enemies',
    category: 'NETWORK',
    tier: 'advanced',
    icon: 'Waves',
    color: '#3B82F6',
    synergyTags: ['aoe', 'slow', 'flood'],
    recommendedWith: ['pool', 'airdrop'],
  },
  {
    id: 'dns_spoof' as WeaponType,
    name: '이간책',
    nameEn: 'Divide & Conquer',
    description: '외교적 기만으로 적끼리 서로 공격하게 만든다',
    descriptionEn: 'Diplomatic deception turns enemies against each other',
    category: 'NETWORK',
    tier: 'advanced',
    icon: 'Shuffle',
    color: '#F59E0B',
    synergyTags: ['debuff', 'confusion', 'utility'],
    recommendedWith: ['deepfake', 'encryption'],
  },
  {
    id: 'packet_loss' as WeaponType,
    name: '외교적 면책',
    nameEn: 'Diplomatic Immunity',
    description: '외교적 보호로 적의 공격을 무효화할 확률',
    descriptionEn: 'Diplomatic protection grants chance to nullify enemy attacks',
    category: 'NETWORK',
    tier: 'advanced',
    icon: 'WifiOff',
    color: '#EF4444',
    synergyTags: ['defensive', 'evasion', 'utility'],
    recommendedWith: ['firewall_surge', 'sandbox'],
  },
  {
    id: 'vpn_tunnel' as WeaponType,
    name: '비밀 경로',
    nameEn: 'Secret Passage',
    description: '비밀 외교 루트를 통한 순간이동. 흔적에 피해',
    descriptionEn: 'Teleport through secret diplomatic routes. Leave damage in path',
    category: 'NETWORK',
    tier: 'elite',
    icon: 'Route',
    color: '#10B981',
    synergyTags: ['mobility', 'zone', 'escape'],
    recommendedWith: ['pool', 'overclock'],
  },
  {
    id: 'ddos' as WeaponType,
    name: '유엔 결의',
    nameEn: 'UN Resolution',
    description: '전 세계가 규탄하는 대규모 연합 공격',
    descriptionEn: 'Massive coalition attack condemned by the entire world',
    category: 'NETWORK',
    tier: 'elite',
    icon: 'Bomb',
    color: '#EF4444',
    synergyTags: ['ultimate', 'aoe', 'powerful'],
    recommendedWith: ['tcp_flood', 'airdrop'],
  },
  {
    id: 'p2p' as WeaponType,
    name: '망명자 영입',
    nameEn: 'Defector Recruit',
    description: '처치한 적이 동맹으로 투항. 아군으로 전투',
    descriptionEn: 'Defeated enemies defect to your alliance. Fight as allies',
    category: 'NETWORK',
    tier: 'elite',
    icon: 'Users',
    color: '#8B5CF6',
    synergyTags: ['summon', 'conversion', 'scaling'],
    recommendedWith: ['neural_net', 'autopilot'],
  },
];

// ============================================
// SOVEREIGNTY (주권) Category Skills (9 skills) — SECURITY
// ============================================

export const SECURITY_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'garlic' as WeaponType,
    name: '국경 수비대',
    nameEn: 'Border Guard',
    description: '국경을 지키는 수비대. 접근하는 침입자에게 지속 피해',
    descriptionEn: 'Border guard defending sovereignty. Sustained damage to approaching invaders',
    category: 'SECURITY',
    tier: 'basic',
    icon: 'Shield',
    color: '#22C55E',
    synergyTags: ['aura', 'defensive', 'sustained'],
    recommendedWith: ['bible', 'pool'],
  },
  // === New Skills ===
  {
    id: 'antivirus' as WeaponType,
    name: '국민 의료',
    nameEn: 'National Healthcare',
    description: '국민 건강보험의 힘. 주기적 치료 + 상태이상 해제',
    descriptionEn: 'Power of national healthcare. Periodic healing + debuff cleanse',
    category: 'SECURITY',
    tier: 'basic',
    icon: 'ShieldCheck',
    color: '#10B981',
    synergyTags: ['heal', 'cleanse', 'defensive'],
    recommendedWith: ['hotfix', 'garlic'],
  },
  {
    id: 'sandbox' as WeaponType,
    name: '격리 봉쇄',
    nameEn: 'Quarantine Zone',
    description: '침입자를 격리 봉쇄. 이동 불가 + 추가 데미지',
    descriptionEn: 'Quarantine invaders. Prevents movement + bonus damage',
    category: 'SECURITY',
    tier: 'basic',
    icon: 'Box',
    color: '#F59E0B',
    synergyTags: ['cc', 'trap', 'utility'],
    recommendedWith: ['pool', 'tcp_flood'],
  },
  {
    id: 'encryption' as WeaponType,
    name: '국가 기밀',
    nameEn: 'State Secret',
    description: '기밀 보호 체계로 받는 피해 감소. 완전 무효화 확률',
    descriptionEn: 'State secrets reduce incoming damage. Chance to nullify completely',
    category: 'SECURITY',
    tier: 'advanced',
    icon: 'Lock',
    color: '#8B5CF6',
    synergyTags: ['defensive', 'damage_reduction', 'evasion'],
    recommendedWith: ['packet_loss', 'firewall_surge'],
  },
  {
    id: 'firewall_surge' as WeaponType,
    name: '독립 선언',
    nameEn: 'Declaration of Independence',
    description: '주권의 폭발! 주변 침략자를 밀어내며 피해',
    descriptionEn: 'Sovereignty explosion! Blasts away nearby invaders',
    category: 'SECURITY',
    tier: 'advanced',
    icon: 'Flame',
    color: '#EF4444',
    synergyTags: ['aoe', 'knockback', 'burst'],
    recommendedWith: ['garlic', 'pool'],
  },
  {
    id: 'zero_trust' as WeaponType,
    name: '불가침 조약',
    nameEn: 'Non-Aggression Pact',
    description: '최초 공격은 항상 무효화. 조약을 어기는 자에게 벌',
    descriptionEn: 'First strike always nullified. Punish those who break the pact',
    category: 'SECURITY',
    tier: 'advanced',
    icon: 'ShieldAlert',
    color: '#06B6D4',
    synergyTags: ['defensive', 'immunity', 'utility'],
    recommendedWith: ['encryption', 'antivirus'],
  },
  {
    id: 'honeypot' as WeaponType,
    name: '함정 도시',
    nameEn: 'Potemkin Village',
    description: '가짜 도시로 적을 유인. 함정에 빠진 적에게 추가 피해',
    descriptionEn: 'Lure enemies with a fake city. Bonus damage to trapped enemies',
    category: 'SECURITY',
    tier: 'elite',
    icon: 'Target',
    color: '#F59E0B',
    synergyTags: ['trap', 'lure', 'utility'],
    recommendedWith: ['sandbox', 'pool'],
  },
  {
    id: 'incident_response' as WeaponType,
    name: '계엄령',
    nameEn: 'Martial Law',
    description: '위기 시 자동 발동! 긴급 국가 회복 + 무적 시간',
    descriptionEn: 'Auto-trigger in crisis! Emergency national recovery + invincibility',
    category: 'SECURITY',
    tier: 'elite',
    icon: 'Siren',
    color: '#EF4444',
    synergyTags: ['heal', 'emergency', 'survival'],
    recommendedWith: ['hotfix', 'antivirus'],
  },
  {
    id: 'backup' as WeaponType,
    name: '임시 정부',
    nameEn: 'Government in Exile',
    description: '수도 함락되어도 망명 정부가 부활. 부활 시 역습',
    descriptionEn: 'Even if capital falls, exile government revives. Counterattack on revive',
    category: 'SECURITY',
    tier: 'elite',
    icon: 'RotateCcw',
    color: '#10B981',
    synergyTags: ['revive', 'emergency', 'survival'],
    recommendedWith: ['incident_response', 'hotfix'],
  },
];

// ============================================
// INTELLIGENCE (정보력) Category Skills (9 skills) — AI
// ============================================

export const AI_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'lightning' as WeaponType,
    name: '천벌',
    nameEn: 'Divine Punishment',
    description: '위성에서 내리꽂는 번개. 정보력이 곧 천벌이다',
    descriptionEn: 'Lightning from orbit. Intelligence IS divine punishment',
    category: 'AI',
    tier: 'basic',
    icon: 'Zap',
    color: '#F59E0B',
    synergyTags: ['auto', 'homing', 'chain'],
    recommendedWith: ['wand', 'neural_net'],
  },
  {
    id: 'beam' as WeaponType,
    name: '위성 레이저',
    nameEn: 'Satellite Laser',
    description: '정찰 위성의 레이저 빔. 적을 관통하며 추적',
    descriptionEn: 'Recon satellite laser beam. Pierces and tracks enemies',
    category: 'AI',
    tier: 'advanced',
    icon: 'Layers',
    color: '#F59E0B',
    synergyTags: ['beam', 'pierce', 'sustained'],
    recommendedWith: ['laser', 'compiler'],
  },
  {
    id: 'laser' as WeaponType,
    name: '감시 레이더',
    nameEn: 'Surveillance Radar',
    description: '360도 회전 레이더. 스캔 범위 내 모든 적에게 피해',
    descriptionEn: '360-degree radar sweep. Damages all enemies in scan range',
    category: 'AI',
    tier: 'advanced',
    icon: 'Repeat',
    color: '#F59E0B',
    synergyTags: ['spin', 'sustained', 'sweep'],
    recommendedWith: ['beam', 'whip'],
  },
  // === New Skills ===
  {
    id: 'neural_net' as WeaponType,
    name: '첩보망',
    nameEn: 'Spy Network',
    description: '세계 곳곳의 첩보원이 정보를 수집. 시간이 갈수록 강력',
    descriptionEn: 'Global spy network gathers intelligence. Scales with time',
    category: 'AI',
    tier: 'basic',
    icon: 'Brain',
    color: '#F59E0B',
    synergyTags: ['scaling', 'auto', 'passive'],
    recommendedWith: ['lightning', 'autopilot'],
  },
  {
    id: 'chatgpt' as WeaponType,
    name: '프로파간다',
    nameEn: 'Propaganda',
    description: '선전 방송으로 적의 사기를 꺾어 행동 정지',
    descriptionEn: 'Propaganda broadcast breaks enemy morale. Stuns for duration',
    category: 'AI',
    tier: 'advanced',
    icon: 'MessageSquare',
    color: '#10B981',
    synergyTags: ['cc', 'stun', 'debuff'],
    recommendedWith: ['dns_spoof', 'sandbox'],
  },
  {
    id: 'autopilot' as WeaponType,
    name: '킬러 드론',
    nameEn: 'Killer Drone',
    description: '자율 비행하는 암살 드론. 표적을 끝까지 추적',
    descriptionEn: 'Autonomous assassination drone. Relentlessly tracks targets',
    category: 'AI',
    tier: 'basic',
    icon: 'Plane',
    color: '#06B6D4',
    synergyTags: ['summon', 'auto', 'homing'],
    recommendedWith: ['lightning', 'neural_net'],
  },
  {
    id: 'deepfake' as WeaponType,
    name: '도플갱어 작전',
    nameEn: 'Doppelgänger Op',
    description: '자신의 분신을 생성. 분신도 전투하며 적의 화력 분산',
    descriptionEn: 'Create a doppelgänger. Clone fights and draws enemy fire',
    category: 'AI',
    tier: 'advanced',
    icon: 'Copy',
    color: '#8B5CF6',
    synergyTags: ['summon', 'decoy', 'utility'],
    recommendedWith: ['honeypot', 'p2p'],
  },
  {
    id: 'singularity_core' as WeaponType,
    name: '블랙사이트',
    nameEn: 'Black Site',
    description: '비밀 시설의 중력장. 적을 빨아들여 집중 데미지',
    descriptionEn: 'Black site gravity field. Pulls enemies in for concentrated damage',
    category: 'AI',
    tier: 'elite',
    icon: 'Circle',
    color: '#1F2937',
    synergyTags: ['pull', 'aoe', 'powerful'],
    recommendedWith: ['ddos', 'big_data'],
  },
  {
    id: 'agi' as WeaponType,
    name: '전지적 시점',
    nameEn: 'Omniscient View',
    description: '모든 것을 파악한 정보국. INTEL 스킬 데미지 2배',
    descriptionEn: 'All-knowing intelligence bureau. Double INTEL skill damage',
    category: 'AI',
    tier: 'elite',
    icon: 'Sparkles',
    color: '#F59E0B',
    synergyTags: ['ultimate', 'buff', 'synergy'],
    recommendedWith: ['neural_net', 'singularity_core'],
  },
];

// ============================================
// MORALE (사기) Category Skills (9 skills) — SYSTEM
// ============================================

export const SYSTEM_SKILLS: SkillDefinition[] = [
  // === Existing ===
  {
    id: 'punch' as WeaponType,
    name: '국민 분노',
    nameEn: "People's Rage",
    description: '침략에 분노한 국민의 주먹. 강한 넉백',
    descriptionEn: 'Fist of the enraged people against invaders. Strong knockback',
    category: 'SYSTEM',
    tier: 'basic',
    icon: 'Keyboard',
    color: '#06B6D4',
    synergyTags: ['melee', 'knockback', 'basic'],
    recommendedWith: ['whip', 'sword'],
  },
  {
    id: 'sword' as WeaponType,
    name: '영웅의 검',
    nameEn: "Hero's Blade",
    description: '국가 영웅이 남긴 명검. 높은 크리티컬 확률',
    descriptionEn: 'Legendary blade of a national hero. High critical chance',
    category: 'SYSTEM',
    tier: 'advanced',
    icon: 'Sword',
    color: '#06B6D4',
    synergyTags: ['melee', 'crit', 'precise'],
    recommendedWith: ['punch', 'focus'],
  },
  {
    id: 'focus' as WeaponType,
    name: '결사 항전',
    nameEn: 'Last Stand',
    description: '죽을 각오로 집중. 크리티컬 확률 대폭 증가',
    descriptionEn: 'Fight to the death focus. Greatly increases critical chance',
    category: 'SYSTEM',
    tier: 'basic',
    icon: 'Focus',
    color: '#06B6D4',
    synergyTags: ['buff', 'crit', 'passive'],
    recommendedWith: ['sword', 'overclock'],
  },
  {
    id: 'overclock' as WeaponType,
    name: '진군 나팔',
    nameEn: 'Battle Horn',
    description: '돌격 나팔이 울린다! 전군 이동속도 증가',
    descriptionEn: 'The battle horn sounds! Increases movement speed',
    category: 'SYSTEM',
    tier: 'basic',
    icon: 'Gauge',
    color: '#06B6D4',
    synergyTags: ['buff', 'speed', 'passive'],
    recommendedWith: ['focus', 'ram_upgrade'],
  },
  // === New Skills ===
  {
    id: 'ram_upgrade' as WeaponType,
    name: '국민 지지',
    nameEn: 'Public Support',
    description: '국민의 지지가 방탄복이 된다. 최대 체력 증가',
    descriptionEn: 'Public support becomes armor. Increases max HP',
    category: 'SYSTEM',
    tier: 'basic',
    icon: 'HardDrive',
    color: '#06B6D4',
    synergyTags: ['buff', 'hp', 'passive'],
    recommendedWith: ['overclock', 'cpu_boost'],
  },
  {
    id: 'cpu_boost' as WeaponType,
    name: '전쟁 광기',
    nameEn: 'War Frenzy',
    description: '전장의 아드레날린. 공격 속도 폭발적 증가',
    descriptionEn: 'Battlefield adrenaline. Explosive attack speed increase',
    category: 'SYSTEM',
    tier: 'advanced',
    icon: 'Cpu',
    color: '#EF4444',
    synergyTags: ['buff', 'attack_speed', 'passive'],
    recommendedWith: ['overclock', 'multithreading'],
  },
  {
    id: 'cache' as WeaponType,
    name: '군수 보급',
    nameEn: 'Supply Drop',
    description: '적시 보급으로 쿨다운 감소. 연속 공격 강화',
    descriptionEn: 'Timely supply drops reduce cooldown. Boost consecutive attacks',
    category: 'SYSTEM',
    tier: 'advanced',
    icon: 'Database',
    color: '#8B5CF6',
    synergyTags: ['buff', 'cooldown', 'combo'],
    recommendedWith: ['refactor', 'cpu_boost'],
  },
  {
    id: 'multithreading' as WeaponType,
    name: '총동원령',
    nameEn: 'General Mobilization',
    description: '전 국민 동원! 동시에 여러 공격 실행',
    descriptionEn: 'Total national mobilization! Execute multiple attacks simultaneously',
    category: 'SYSTEM',
    tier: 'elite',
    icon: 'Layers',
    color: '#F59E0B',
    synergyTags: ['buff', 'multi', 'passive'],
    recommendedWith: ['fork', 'shard'],
  },
  {
    id: 'garbage_collection' as WeaponType,
    name: '전쟁 배상금',
    nameEn: 'War Reparations',
    description: '적을 처치하면 배상금 회수. 체력 회복 + 경험치',
    descriptionEn: 'Collect war reparations on kill. Heal HP + bonus EXP',
    category: 'SYSTEM',
    tier: 'elite',
    icon: 'Trash2',
    color: '#06B6D4',
    synergyTags: ['heal', 'exp', 'scaling'],
    recommendedWith: ['antivirus', 'ram_upgrade'],
  },
];

// ============================================
// Aggregated Exports
// ============================================

/**
 * 모든 스킬 정의 (55개)
 */
export const ALL_SKILLS: SkillDefinition[] = [
  ...CODE_SKILLS,
  ...DATA_SKILLS,
  ...NETWORK_SKILLS,
  ...SECURITY_SKILLS,
  ...AI_SKILLS,
  ...SYSTEM_SKILLS,
];

/**
 * 카테고리별 스킬 맵
 */
export const SKILLS_BY_CATEGORY: Record<SkillCategory, SkillDefinition[]> = {
  CODE: CODE_SKILLS,
  DATA: DATA_SKILLS,
  NETWORK: NETWORK_SKILLS,
  SECURITY: SECURITY_SKILLS,
  AI: AI_SKILLS,
  SYSTEM: SYSTEM_SKILLS,
};

/**
 * 스킬 ID로 정의 찾기
 */
export const SKILL_MAP: Record<string, SkillDefinition> = Object.fromEntries(
  ALL_SKILLS.map(skill => [skill.id, skill])
);

/**
 * 티어별 스킬 필터링
 */
export const getSkillsByTier = (tier: 'basic' | 'advanced' | 'elite'): SkillDefinition[] =>
  ALL_SKILLS.filter(skill => skill.tier === tier);

/**
 * 시너지 태그로 스킬 찾기
 */
export const getSkillsBySynergyTag = (tag: string): SkillDefinition[] =>
  ALL_SKILLS.filter(skill => skill.synergyTags?.includes(tag));

export default ALL_SKILLS;
