/**
 * skins.config.ts - CODE SURVIVOR 스킨 설정
 * Matrix/Developer 테마 - 72개 스킨 (캐릭터당 8개)
 *
 * NOTE: name, description은 i18n으로 관리됩니다.
 *       t.skins[skinId].name, t.skins[skinId].desc 사용
 *
 * 스킨 능력치 보너스 기준:
 * - Common: 없음 (기본 스킨)
 * - Rare: 1-2개 능력치 (3-5%)
 * - Epic: 2개 능력치 (4-7%)
 * - Legendary: 2-3개 능력치 (8-15%) + 보너스 스킬
 *
 * 테마 카테고리:
 * - Default: 일상 개발자 복장
 * - Corporate: FAANG/스타트업 스타일
 * - Retro: 90년대 해커/개발자
 * - Cyberpunk: 네온, 사이버웨어
 * - Matrix: 롱코트, 선글라스, 코드비
 * - Mastery: 캐릭터별 최종 형태
 */

import { type Skin, type SkinRarity } from '../types';
export type { Skin, SkinRarity };
import { PlayerClass } from '../types';

// 스킨 카테고리 타입
export type SkinCategory = 'default' | 'corporate' | 'retro' | 'cyberpunk' | 'matrix' | 'mastery';

// 전체 스킨 목록
export const SKINS: Skin[] = [
  // =============================================================================
  // NEO (validator) - 각성한 풀스택 개발자
  // =============================================================================
  {
    id: 'neo_default',
    characterId: 'neo',
    name: 'Startup Dev',
    description: '스타트업 개발자의 기본 복장 - 흰 셔츠',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#f8fafc',      // 흰 셔츠
      pants: '#1e293b',     // 네이비 바지
      hair: '#1f2120',      // 검은 머리
      accent: '#64748b',    // 셔츠 칼라/단추용
      shoes: '#111827',     // 검은 신발
      outfit: 'shirt',      // 셔츠 스타일
      accessoryType: 'none',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'neo_coffee',
    characterId: 'neo',
    name: 'Coffee Addict',
    description: '커피 없인 못 사는 개발자. 이동속도 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#374151',
      pants: '#1e3a5f',
      hair: '#1a1a2e',
      accent: '#8b5a2b',
      shoes: '#1f2937',
      outfit: 'hoodie',
      accessoryType: 'coffee_mug',
      pattern: 'none',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 3 },
  },
  {
    id: 'neo_google',
    characterId: 'neo',
    name: 'Google Engineer',
    description: '빅테크 엔지니어 스타일. 경험치 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#4285F4',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#DB4437',
      shoes: '#1a1a1a',
      outfit: 'jacket',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#FBBC04',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 4 },
  },
  {
    id: 'neo_agent',
    characterId: 'neo',
    name: 'Matrix Agent',
    description: '매트릭스 요원 복장. 공격력 +5%, 이동속도 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#0a0a0a',
      pants: '#0a0a0a',
      hair: '#1a1a2e',
      accent: '#00FF41',
      shoes: '#000000',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'none',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 5, spdBonus: 5 },
  },
  {
    id: 'neo_cyber',
    characterId: 'neo',
    name: 'Cyber Hacker',
    description: '사이버펑크 해커. 공격력 +6%, 치명타 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#BF00FF',
      pants: '#1a1a2e',
      hair: '#00FFFF',
      accent: '#FF00FF',
      shoes: '#1f2937',
      outfit: 'cyber_suit',
      accessoryType: 'vr_headset',
      pattern: 'neon_lines',
      patternColor: '#00FFFF',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 6, critBonus: 4 },
  },
  {
    id: 'neo_one',
    characterId: 'neo',
    name: 'The One',
    description: '그가 바로 "그 사람". 공격력 +10%, HP +8% + 불굴',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#f5f5f5',
      pants: '#e5e5e5',
      hair: '#1a1a2e',
      accent: '#00FF41',
      shoes: '#ffffff',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'matrix_rain',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 10, hpBonus: 8 },
    bonusSkill: {
      id: 'skill_unyielding',
      name: '불굴의 의지 + 방어막',
      description: 'HP 20% 이하 시 받는 피해 50% 감소. 게임 시작 시 방어막 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'stablecoin',
      weaponLevel: 1,
      effectParams: { value: 50, chance: 100 },
    },
  },
  {
    id: 'neo_code',
    characterId: 'neo',
    name: 'Code Master',
    description: '코드를 지배하는 자. 공격력 +8%, 이동속도 +10% + 번개',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#008F11',
      pants: '#004d00',
      hair: '#00FF41',
      accent: '#39FF14',
      shoes: '#003300',
      outfit: 'future_suit',
      accessoryType: 'data_stream',
      pattern: 'code',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, spdBonus: 10 },
    bonusSkill: {
      id: 'skill_lightning',
      name: '코드 번개',
      description: '코드로 번개를 소환한다. 게임 시작 시 번개 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'lightning',
      weaponLevel: 1,
      effectParams: { value: 20 },
    },
  },
  {
    id: 'neo_god',
    characterId: 'neo',
    name: 'Digital God',
    description: '디지털 세계의 신. 전체 능력 +8% + 방어막',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_neo' },
    colors: {
      body: '#00FFFF',
      pants: '#00CED1',
      hair: '#E0FFFF',
      accent: '#FFD700',
      shoes: '#00CED1',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'data_flow',
      patternColor: '#00FFFF',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, hpBonus: 8, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_digital_shield',
      name: '디지털 방어막',
      description: '데이터로 이루어진 절대 방어막. 게임 시작 시 방어막 Lv.2 획득',
      type: 'start_weapon',
      weaponType: 'stablecoin',
      weaponLevel: 2,
      effectParams: { value: 100, chance: 100 },
    },
  },

  // =============================================================================
  // TANK (miner) - DevOps 엔지니어
  // =============================================================================
  {
    id: 'tank_default',
    characterId: 'tank',
    name: 'Server Admin',
    description: '서버실을 지키는 관리자',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#FF9900',
      pants: '#232F3E',
      hair: '#1a1a1a',
      accent: '#ffffff',
      shoes: '#1a1a1a',
      outfit: 'tactical',
      accessoryType: 'server_badge',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'tank_aws',
    characterId: 'tank',
    name: 'AWS Certified',
    description: 'AWS 인증 클라우드 전문가. HP +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#FF9900',
      pants: '#232F3E',
      hair: '#1a1a1a',
      accent: '#ffffff',
      shoes: '#1f2937',
      outfit: 'jacket',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#FF9900',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { hpBonus: 4 },
  },
  {
    id: 'tank_retro',
    characterId: 'tank',
    name: '90s Sysadmin',
    description: '90년대 시스템 관리자. 방어력 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#6b7280',
      pants: '#374151',
      hair: '#1a1a1a',
      accent: '#fbbf24',
      shoes: '#1f2937',
      outfit: 'retro_uniform',
      accessoryType: 'glasses',
      pattern: 'stripes',
      patternColor: '#9ca3af',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { defBonus: 3 },
  },
  {
    id: 'tank_guardian',
    characterId: 'tank',
    name: 'Cyber Guardian',
    description: '사이버 수호자. HP +6%, 방어력 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#0ea5e9',
      pants: '#0369a1',
      hair: '#1a1a1a',
      accent: '#38bdf8',
      shoes: '#0c4a6e',
      outfit: 'server_armor',
      accessoryType: 'helmet',
      pattern: 'circuit',
      patternColor: '#38bdf8',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { hpBonus: 6, defBonus: 5 },
  },
  {
    id: 'tank_firewall',
    characterId: 'tank',
    name: 'Firewall Titan',
    description: '방화벽의 화신. HP +7%, 공격력 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#dc2626',
      pants: '#7f1d1d',
      hair: '#1a1a1a',
      accent: '#fbbf24',
      shoes: '#991b1b',
      outfit: 'server_armor',
      accessoryType: 'helmet',
      pattern: 'binary',
      patternColor: '#f97316',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { hpBonus: 7, atkBonus: 4 },
  },
  {
    id: 'tank_server',
    characterId: 'tank',
    name: 'Server God',
    description: '서버의 신. HP +12%, 방어력 +8% + 펀치',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#4ade80',
      pants: '#166534',
      hair: '#1a1a1a',
      accent: '#00FF41',
      shoes: '#14532d',
      outfit: 'server_armor',
      accessoryType: 'cape',
      pattern: 'data_flow',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { hpBonus: 12, defBonus: 8 },
    bonusSkill: {
      id: 'skill_server_punch',
      name: '서버 펀치',
      description: '서버의 힘으로 적을 날린다. 게임 시작 시 펀치 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'punch',
      weaponLevel: 1,
      effectParams: { value: 50 },
    },
  },
  {
    id: 'tank_infra',
    characterId: 'tank',
    name: 'Infrastructure',
    description: '인프라의 화신. HP +10%, 공격력 +8% + 힐링풀',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#00FFFF',
      pants: '#0e7490',
      hair: '#1a1a1a',
      accent: '#22d3ee',
      shoes: '#155e75',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'neon_lines',
      patternColor: '#00FFFF',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { hpBonus: 10, atkBonus: 8 },
    bonusSkill: {
      id: 'skill_healing_pool',
      name: '인프라 회복',
      description: '인프라의 힘으로 회복한다. 게임 시작 시 흡혈풀 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'pool',
      weaponLevel: 1,
      effectParams: { value: 5 },
    },
  },
  {
    id: 'tank_diamond',
    characterId: 'tank',
    name: 'Unbreakable',
    description: '부서지지 않는 자. HP +15% + 킬시 HP회복',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_tank' },
    colors: {
      body: '#60a5fa',
      pants: '#3b82f6',
      hair: '#93c5fd',
      accent: '#dbeafe',
      shoes: '#2563eb',
      outfit: 'future_suit',
      accessoryType: 'crown',
      pattern: 'sparkle',
      patternColor: '#ffffff',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { hpBonus: 15 },
    bonusSkill: {
      id: 'skill_diamond_recovery',
      name: '다이아몬드 회복',
      description: '적 처치 시 최대 HP의 1% 회복',
      type: 'on_kill',
      effectParams: { value: 1, chance: 100 },
    },
  },

  // =============================================================================
  // CYPHER (trader) - 프론트엔드 개발자
  // =============================================================================
  {
    id: 'cypher_default',
    characterId: 'cypher',
    name: 'UI Designer',
    description: 'UI/UX 디자이너의 캐주얼 복장',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#8b5cf6',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#c4b5fd',
      shoes: '#374151',
      outfit: 'business',
      accessoryType: 'watch',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'cypher_ceo',
    characterId: 'cypher',
    name: 'Startup CEO',
    description: '스타트업 CEO 정장. 골드 +5%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#1e293b',
      pants: '#0f172a',
      hair: '#1a1a2e',
      accent: '#64748b',
      shoes: '#1a1a1a',
      outfit: 'suit',
      accessoryType: 'watch',
      pattern: 'none',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { goldBonus: 5 },
  },
  {
    id: 'cypher_retro',
    characterId: 'cypher',
    name: 'Retro Webmaster',
    description: '90년대 웹마스터. 이동속도 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#3b82f6',
      pants: '#374151',
      hair: '#1a1a2e',
      accent: '#60a5fa',
      shoes: '#1f2937',
      outfit: 'retro_uniform',
      accessoryType: 'glasses',
      pattern: 'stripes',
      patternColor: '#93c5fd',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 3 },
  },
  {
    id: 'cypher_double',
    characterId: 'cypher',
    name: 'Double Agent',
    description: '이중 요원. 이동속도 +5%, 회피율 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#f5f5f5',
      pants: '#0a0a0a',
      hair: '#6b7280',
      accent: '#9ca3af',
      shoes: '#374151',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'gradient',
      patternColor: '#1a1a1a',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 5, dodgeBonus: 5 },
  },
  {
    id: 'cypher_neon',
    characterId: 'cypher',
    name: 'Neon Runner',
    description: '네온 러너. 이동속도 +6%, 골드 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#FF00FF',
      pants: '#1a1a2e',
      hair: '#00FFFF',
      accent: '#BF00FF',
      shoes: '#1f2937',
      outfit: 'cyber_suit',
      accessoryType: 'holo_visor',
      pattern: 'neon_lines',
      patternColor: '#00FFFF',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 6, goldBonus: 4 },
  },
  {
    id: 'cypher_redeemed',
    characterId: 'cypher',
    name: 'Betrayer Redeemed',
    description: '속죄한 배신자. 이동속도 +10%, 골드 +10% + 오라클',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#f5f5f5',
      pants: '#1a1a2e',
      hair: '#e5e5e5',
      accent: '#fbbf24',
      shoes: '#374151',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'gradient',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { spdBonus: 10, goldBonus: 10 },
    bonusSkill: {
      id: 'skill_oracle_vision',
      name: '오라클 비전',
      description: '속죄의 눈으로 미래를 본다. 게임 시작 시 오라클 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'oracle',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'cypher_rich',
    characterId: 'cypher',
    name: 'Money Maker',
    description: '황금 슈트. 골드 +20%, 이동속도 +8% + 샤드',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'gold_1m' },
    colors: {
      body: '#FFD700',
      pants: '#B8860B',
      hair: '#FFA500',
      accent: '#FFFACD',
      shoes: '#DAA520',
      outfit: 'future_suit',
      accessoryType: 'crown',
      pattern: 'sparkle',
      patternColor: '#FFD700',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { goldBonus: 20, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_golden_shard',
      name: '황금 샤드',
      description: '황금 결정을 발사한다. 게임 시작 시 샤드 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'shard',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'cypher_speed',
    characterId: 'cypher',
    name: 'Speed Demon',
    description: '번개처럼 빠른 자. 이동속도 +15%, 회피율 +10%',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_cypher' },
    colors: {
      body: '#fbbf24',
      pants: '#f59e0b',
      hair: '#fef08a',
      accent: '#fef3c7',
      shoes: '#d97706',
      outfit: 'cyber_suit',
      accessoryType: 'data_stream',
      pattern: 'neon_lines',
      patternColor: '#fbbf24',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { spdBonus: 15, dodgeBonus: 10 },
    bonusSkill: {
      id: 'skill_speed_afterimage',
      name: '잔상',
      description: '회피 성공 시 3초간 이동속도 30% 증가',
      type: 'on_damage',
      effectParams: { value: 30, duration: 3, chance: 100 },
    },
  },

  // =============================================================================
  // MORPHEUS (eric) - 시니어 아키텍트
  // =============================================================================
  {
    id: 'morpheus_default',
    characterId: 'morpheus',
    name: 'Senior Dev',
    description: '시니어 개발자의 비즈니스 캐주얼',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#1e293b',
      pants: '#0f172a',
      hair: '#d4d4d4',
      accent: '#64748b',
      shoes: '#1a1a1a',
      outfit: 'business',
      accessoryType: 'glasses',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'morpheus_legacy',
    characterId: 'morpheus',
    name: 'Legacy Master',
    description: '레거시 코드의 달인. 공격력 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#6b7280',
      pants: '#374151',
      hair: '#d4d4d4',
      accent: '#9ca3af',
      shoes: '#1f2937',
      outfit: 'retro_uniform',
      accessoryType: 'glasses',
      pattern: 'code',
      patternColor: '#4b5563',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 3 },
  },
  {
    id: 'morpheus_lead',
    characterId: 'morpheus',
    name: 'Tech Lead',
    description: '테크 리드. 경험치 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#4285F4',
      pants: '#1e1e1e',
      hair: '#d4d4d4',
      accent: '#60a5fa',
      shoes: '#1a1a1a',
      outfit: 'business',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#3b82f6',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 4 },
  },
  {
    id: 'morpheus_captain',
    characterId: 'morpheus',
    name: 'Ship Captain',
    description: '배의 선장. 공격력 +5%, HP +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#1e3a5f',
      pants: '#0f172a',
      hair: '#d4d4d4',
      accent: '#fbbf24',
      shoes: '#1a1a1a',
      outfit: 'matrix_coat',
      accessoryType: 'helmet',
      pattern: 'stripes',
      patternColor: '#fbbf24',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 5, hpBonus: 5 },
  },
  {
    id: 'morpheus_truth',
    characterId: 'morpheus',
    name: 'Truth Seeker',
    description: '진실을 추구하는 자. 공격력 +6%, 이동속도 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#7c3aed',
      pants: '#4c1d95',
      hair: '#d4d4d4',
      accent: '#a78bfa',
      shoes: '#5b21b6',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'matrix_rain',
      patternColor: '#a78bfa',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 6, spdBonus: 4 },
  },
  {
    id: 'morpheus_mentor',
    characterId: 'morpheus',
    name: 'The Mentor',
    description: '멘토. 공격력 +10%, HP +8% + 빔',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#0a0a0a',
      pants: '#0a0a0a',
      hair: '#d4d4d4',
      accent: '#00FF41',
      shoes: '#000000',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'matrix_rain',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 10, hpBonus: 8 },
    bonusSkill: {
      id: 'skill_mentor_beam',
      name: '멘토의 빔',
      description: '지식의 빔을 발사한다. 게임 시작 시 빔 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'beam',
      weaponLevel: 1,
      effectParams: { value: 50, duration: 5 },
    },
  },
  {
    id: 'morpheus_arch',
    characterId: 'morpheus',
    name: 'Architect',
    description: '아키텍트. 공격력 +8%, 공속 +10% + 피싱',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#1e40af',
      pants: '#1e3a8a',
      hair: '#93c5fd',
      accent: '#3b82f6',
      shoes: '#1e3a8a',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'circuit',
      patternColor: '#60a5fa',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, atkSpeedBonus: 10 },
    bonusSkill: {
      id: 'skill_architect_phishing',
      name: '아키텍트 피싱',
      description: '설계도로 적을 낚는다. 게임 시작 시 피싱 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'phishing',
      weaponLevel: 1,
      effectParams: { value: 15 },
    },
  },
  {
    id: 'morpheus_wisdom',
    characterId: 'morpheus',
    name: 'Wisdom',
    description: '지혜. 전체 능력 +8% + 웨이브 버프',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_morpheus' },
    colors: {
      body: '#f5f5f5',
      pants: '#e5e5e5',
      hair: '#ffffff',
      accent: '#fbbf24',
      shoes: '#d4d4d4',
      outfit: 'future_suit',
      accessoryType: 'crown',
      pattern: 'data_flow',
      patternColor: '#fbbf24',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, hpBonus: 8, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_wisdom_aura',
      name: '지혜의 오라',
      description: '웨이브 시작 시 5초간 모든 능력치 10% 증가',
      type: 'aura',
      effectParams: { value: 10, duration: 5, radius: 300 },
    },
  },

  // =============================================================================
  // NIOBE (zais) - 클라우드 아키텍트
  // =============================================================================
  {
    id: 'niobe_default',
    characterId: 'niobe',
    name: 'Cloud Engineer',
    description: '클라우드 엔지니어의 테크 캐주얼',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#0ea5e9',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#38bdf8',
      shoes: '#374151',
      outfit: 'business',
      accessoryType: 'server_badge',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'niobe_aws',
    characterId: 'niobe',
    name: 'AWS Architect',
    description: 'AWS 아키텍트. 이동속도 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#FF9900',
      pants: '#232F3E',
      hair: '#1a1a2e',
      accent: '#ffffff',
      shoes: '#1f2937',
      outfit: 'jacket',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#FF9900',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 4 },
  },
  {
    id: 'niobe_gcp',
    characterId: 'niobe',
    name: 'GCP Expert',
    description: 'GCP 전문가. 경험치 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#4285F4',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#DB4437',
      shoes: '#1a1a1a',
      outfit: 'business',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#FBBC04',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 3 },
  },
  {
    id: 'niobe_multi',
    characterId: 'niobe',
    name: 'Multi-Cloud',
    description: '멀티 클라우드 마스터. 이동속도 +6%, 회피율 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#7c3aed',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#a78bfa',
      shoes: '#374151',
      outfit: 'cyber_suit',
      accessoryType: 'holo_visor',
      pattern: 'gradient',
      patternColor: '#FF9900',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 6, dodgeBonus: 4 },
  },
  {
    id: 'niobe_pilot',
    characterId: 'niobe',
    name: 'Cyber Pilot',
    description: '사이버 파일럿. 이동속도 +5%, 공격력 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#1e40af',
      pants: '#1e3a8a',
      hair: '#1a1a2e',
      accent: '#3b82f6',
      shoes: '#1e3a8a',
      outfit: 'tactical',
      accessoryType: 'holo_visor',
      pattern: 'neon_lines',
      patternColor: '#60a5fa',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 5, atkBonus: 5 },
  },
  {
    id: 'niobe_goddess',
    characterId: 'niobe',
    name: 'Cloud Goddess',
    description: '클라우드의 여신. 이동속도 +12%, 회피율 +8% + 완드',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#e0f2fe',
      pants: '#bae6fd',
      hair: '#7dd3fc',
      accent: '#0ea5e9',
      shoes: '#38bdf8',
      outfit: 'cloud_cape',
      accessoryType: 'data_stream',
      pattern: 'data_flow',
      patternColor: '#0ea5e9',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: true,
    statBonus: { spdBonus: 12, dodgeBonus: 8 },
    bonusSkill: {
      id: 'skill_cloud_wand',
      name: '클라우드 완드',
      description: '구름의 힘을 담은 완드. 게임 시작 시 완드 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'wand',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'niobe_teleport',
    characterId: 'niobe',
    name: 'Teleporter',
    description: '텔레포터. 이동속도 +10%, HP +8% + 성경',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#BF00FF',
      pants: '#7c3aed',
      hair: '#00FFFF',
      accent: '#FF00FF',
      shoes: '#6d28d9',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'neon_lines',
      patternColor: '#00FFFF',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { spdBonus: 10, hpBonus: 8 },
    bonusSkill: {
      id: 'skill_teleport_bible',
      name: '텔레포트 성경',
      description: '공간을 넘나드는 성경. 게임 시작 시 성경 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'bible',
      weaponLevel: 1,
      effectParams: { value: 5, radius: 250 },
    },
  },
  {
    id: 'niobe_sky',
    characterId: 'niobe',
    name: 'Sky Walker',
    description: '하늘을 걷는 자. 이동속도 +15% + 텔레포트 강화',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_niobe' },
    colors: {
      body: '#fef3c7',
      pants: '#fde68a',
      hair: '#fbbf24',
      accent: '#f59e0b',
      shoes: '#d97706',
      outfit: 'cloud_cape',
      accessoryType: 'crown',
      pattern: 'sparkle',
      patternColor: '#fbbf24',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { spdBonus: 15 },
    bonusSkill: {
      id: 'skill_sky_teleport',
      name: '스카이 텔레포트',
      description: '텔레포트 쿨다운 30% 감소',
      type: 'passive',
      effectParams: { value: 30 },
    },
  },

  // =============================================================================
  // ORACLE (josh) - 데이터 사이언티스트
  // =============================================================================
  {
    id: 'oracle_default',
    characterId: 'oracle',
    name: 'Data Scientist',
    description: '데이터 사이언티스트의 연구원 복장',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#f5f5f5',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#64748b',
      shoes: '#374151',
      outfit: 'lab_coat',
      accessoryType: 'glasses',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'oracle_ml',
    characterId: 'oracle',
    name: 'ML Engineer',
    description: 'ML 엔지니어. 경험치 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#374151',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#9ca3af',
      shoes: '#1f2937',
      outfit: 'hoodie',
      accessoryType: 'headphones',
      pattern: 'code',
      patternColor: '#6b7280',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 4 },
  },
  {
    id: 'oracle_stats',
    characterId: 'oracle',
    name: 'Statistician',
    description: '통계학자. 치명타 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#6b7280',
      pants: '#374151',
      hair: '#1a1a2e',
      accent: '#9ca3af',
      shoes: '#1f2937',
      outfit: 'retro_uniform',
      accessoryType: 'glasses',
      pattern: 'binary',
      patternColor: '#4b5563',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { critBonus: 3 },
  },
  {
    id: 'oracle_prophet',
    characterId: 'oracle',
    name: 'Prophet',
    description: '예언자. 경험치 +6%, 치명타 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#7c3aed',
      pants: '#4c1d95',
      hair: '#a78bfa',
      accent: '#c4b5fd',
      shoes: '#5b21b6',
      outfit: 'matrix_coat',
      accessoryType: 'glasses',
      pattern: 'matrix_rain',
      patternColor: '#a78bfa',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 6, critBonus: 4 },
  },
  {
    id: 'oracle_neural',
    characterId: 'oracle',
    name: 'Neural Network',
    description: '뉴럴 네트워크. 공격력 +5%, 경험치 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#00FFFF',
      pants: '#1a1a2e',
      hair: '#00CED1',
      accent: '#E0FFFF',
      shoes: '#1f2937',
      outfit: 'cyber_suit',
      accessoryType: 'neural_link',
      pattern: 'circuit',
      patternColor: '#00FFFF',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 5, expBonus: 5 },
  },
  {
    id: 'oracle_allknow',
    characterId: 'oracle',
    name: 'All-Knowing',
    description: '전지전능. 경험치 +12%, 치명타 +8% + 오라클 강화',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#00FF41',
      pants: '#008F11',
      hair: '#39FF14',
      accent: '#00FF41',
      shoes: '#004d00',
      outfit: 'future_suit',
      accessoryType: 'data_stream',
      pattern: 'data_flow',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { expBonus: 12, critBonus: 8 },
    bonusSkill: {
      id: 'skill_enhanced_oracle',
      name: '강화된 오라클',
      description: '오라클 효과 50% 증가. 게임 시작 시 오라클 Lv.2 획득',
      type: 'start_weapon',
      weaponType: 'oracle',
      weaponLevel: 2,
      effectParams: { value: 50 },
    },
  },
  {
    id: 'oracle_future',
    characterId: 'oracle',
    name: 'Future Sight',
    description: '미래 예지. 경험치 +10%, HP +8% + 예측',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#3b82f6',
      pants: '#1e40af',
      hair: '#60a5fa',
      accent: '#93c5fd',
      shoes: '#1e3a8a',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'neon_lines',
      patternColor: '#60a5fa',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { expBonus: 10, hpBonus: 8 },
    bonusSkill: {
      id: 'skill_future_prediction',
      name: '미래 예측',
      description: '웨이브 시작 시 3초간 무적',
      type: 'aura',
      effectParams: { value: 100, duration: 3 },
    },
  },
  {
    id: 'oracle_seer',
    characterId: 'oracle',
    name: 'The Seer',
    description: '예견자. 전체 능력 +8% + 자동회피',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_oracle' },
    colors: {
      body: '#f5f5f5',
      pants: '#e5e5e5',
      hair: '#ffffff',
      accent: '#fbbf24',
      shoes: '#d4d4d4',
      outfit: 'matrix_coat',
      accessoryType: 'crown',
      pattern: 'sparkle',
      patternColor: '#fbbf24',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, hpBonus: 8, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_auto_dodge',
      name: '자동 회피',
      description: '치명적 공격을 30% 확률로 자동 회피',
      type: 'on_damage',
      effectParams: { value: 30, chance: 30 },
    },
  },

  // =============================================================================
  // TRINITY (aiden) - 사이버 보안 전문가
  // =============================================================================
  {
    id: 'trinity_default',
    characterId: 'trinity',
    name: 'White Hat',
    description: '화이트햇 해커의 후디',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#374151',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#9ca3af',
      shoes: '#1f2937',
      outfit: 'hoodie',
      accessoryType: 'laptop_bag',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'trinity_pentest',
    characterId: 'trinity',
    name: 'Pentester',
    description: '펜테스터. 공격력 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#1f2937',
      pants: '#111827',
      hair: '#1a1a2e',
      accent: '#4b5563',
      shoes: '#1f2937',
      outfit: 'tactical',
      accessoryType: 'server_badge',
      pattern: 'code',
      patternColor: '#374151',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 3 },
  },
  {
    id: 'trinity_retro',
    characterId: 'trinity',
    name: '90s Hacker',
    description: '90년대 해커. 이동속도 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#22c55e',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#4ade80',
      shoes: '#1f2937',
      outfit: 'retro_uniform',
      accessoryType: 'glasses',
      pattern: 'binary',
      patternColor: '#22c55e',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { spdBonus: 4 },
  },
  {
    id: 'trinity_blackops',
    characterId: 'trinity',
    name: 'Black Ops',
    description: '블랙옵스. 공격력 +5%, 이동속도 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#0a0a0a',
      pants: '#0a0a0a',
      hair: '#1a1a2e',
      accent: '#374151',
      shoes: '#000000',
      outfit: 'tactical',
      accessoryType: 'helmet',
      pattern: 'none',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 5, spdBonus: 5 },
  },
  {
    id: 'trinity_matrix',
    characterId: 'trinity',
    name: 'Matrix Trinity',
    description: '매트릭스 트리니티. 공격력 +6%, 회피율 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#0a0a0a',
      pants: '#0a0a0a',
      hair: '#1a1a2e',
      accent: '#00FF41',
      shoes: '#000000',
      outfit: 'matrix_coat',
      accessoryType: 'sunglasses',
      pattern: 'matrix_rain',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 6, dodgeBonus: 4 },
  },
  {
    id: 'trinity_breaker',
    characterId: 'trinity',
    name: 'System Breaker',
    description: '시스템 브레이커. 공격력 +10%, 이동속도 +8% + 나이프',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#00FF41',
      pants: '#008F11',
      hair: '#00FF41',
      accent: '#39FF14',
      shoes: '#004d00',
      outfit: 'cyber_suit',
      accessoryType: 'data_stream',
      pattern: 'code',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 10, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_system_knife',
      name: '시스템 나이프',
      description: '시스템을 절단하는 나이프. 게임 시작 시 나이프 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'knife',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'trinity_ghost',
    characterId: 'trinity',
    name: 'Ghost',
    description: '고스트. 공격력 +8%, 회피율 +10% + 회피버프',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#e5e5e5',
      pants: '#d4d4d4',
      hair: '#f5f5f5',
      accent: '#a3a3a3',
      shoes: '#d4d4d4',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'data_flow',
      patternColor: '#a3a3a3',
      glowEffect: 'hologram',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, dodgeBonus: 10 },
    bonusSkill: {
      id: 'skill_ghost_dodge',
      name: '고스트 회피',
      description: '회피 성공 시 3초간 투명화 및 이동속도 50% 증가',
      type: 'on_damage',
      effectParams: { value: 50, duration: 3, chance: 100 },
    },
  },
  {
    id: 'trinity_zeroday',
    characterId: 'trinity',
    name: 'Zero Day',
    description: '제로데이. 공격력 +12%, 치명타 +8% + 방어무시',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_trinity' },
    colors: {
      body: '#dc2626',
      pants: '#7f1d1d',
      hair: '#ef4444',
      accent: '#f87171',
      shoes: '#991b1b',
      outfit: 'cyber_suit',
      accessoryType: 'crown',
      pattern: 'neon_lines',
      patternColor: '#dc2626',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 12, critBonus: 8 },
    bonusSkill: {
      id: 'skill_zero_day',
      name: '제로데이 익스플로잇',
      description: '모든 공격이 적의 방어력 30% 무시',
      type: 'passive',
      effectParams: { value: 30 },
    },
  },

  // =============================================================================
  // MOUSE (david) - 주니어 개발자
  // =============================================================================
  {
    id: 'mouse_default',
    characterId: 'mouse',
    name: 'Intern',
    description: '인턴의 첫 출근 복장',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#3b82f6',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#60a5fa',
      shoes: '#374151',
      outfit: 'tshirt',
      accessoryType: 'laptop_bag',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'mouse_enthusiast',
    characterId: 'mouse',
    name: 'Enthusiast',
    description: 'AI 열정파. 공격속도 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#8b5cf6',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#a78bfa',
      shoes: '#374151',
      outfit: 'hoodie',
      accessoryType: 'headphones',
      pattern: 'code',
      patternColor: '#8b5cf6',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { atkSpeedBonus: 4 },
  },
  {
    id: 'mouse_bootcamp',
    characterId: 'mouse',
    name: 'Bootcamp',
    description: '부트캠프 수료생. 경험치 +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#22c55e',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#4ade80',
      shoes: '#374151',
      outfit: 'tshirt',
      accessoryType: 'server_badge',
      pattern: 'tech_logo',
      patternColor: '#22c55e',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { expBonus: 4 },
  },
  {
    id: 'mouse_rising',
    characterId: 'mouse',
    name: 'Rising Star',
    description: '떠오르는 별. 공격속도 +5%, 경험치 +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#fbbf24',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#fde047',
      shoes: '#374151',
      outfit: 'hoodie',
      accessoryType: 'headphones',
      pattern: 'sparkle',
      patternColor: '#fbbf24',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkSpeedBonus: 5, expBonus: 5 },
  },
  {
    id: 'mouse_fanboy',
    characterId: 'mouse',
    name: 'AI Fanboy',
    description: 'AI 팬보이. 공격속도 +6%, 이동속도 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#00FFFF',
      pants: '#1a1a2e',
      hair: '#00CED1',
      accent: '#E0FFFF',
      shoes: '#1f2937',
      outfit: 'cyber_suit',
      accessoryType: 'vr_headset',
      pattern: 'circuit',
      patternColor: '#00FFFF',
      glowEffect: 'cyber',
    },
    hasSpecialEffect: false,
    statBonus: { atkSpeedBonus: 6, spdBonus: 4 },
  },
  {
    id: 'mouse_pure',
    characterId: 'mouse',
    name: 'Pure Soul',
    description: '순수한 영혼. 공격속도 +12%, 이동속도 +8% + MCP서버',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#f5f5f5',
      pants: '#e5e5e5',
      hair: '#ffffff',
      accent: '#fbbf24',
      shoes: '#d4d4d4',
      outfit: 'future_suit',
      accessoryType: 'data_stream',
      pattern: 'data_flow',
      patternColor: '#fbbf24',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkSpeedBonus: 12, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_mcp_server',
      name: 'MCP 서버',
      description: 'MCP 서버를 소환한다. 게임 시작 시 피싱 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'phishing',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'mouse_prodigy',
    characterId: 'mouse',
    name: 'Prodigy',
    description: '천재. 공격속도 +10%, 경험치 +10% + 공속강화',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#00FF41',
      pants: '#008F11',
      hair: '#39FF14',
      accent: '#00FF41',
      shoes: '#004d00',
      outfit: 'cyber_suit',
      accessoryType: 'neural_link',
      pattern: 'matrix_rain',
      patternColor: '#00FF41',
      glowEffect: 'matrix',
    },
    hasSpecialEffect: true,
    statBonus: { atkSpeedBonus: 10, expBonus: 10 },
    bonusSkill: {
      id: 'skill_prodigy_speed',
      name: '천재의 손',
      description: '레벨업 시 5초간 공격속도 50% 증가',
      type: 'aura',
      effectParams: { value: 50, duration: 5 },
    },
  },
  {
    id: 'mouse_innocent',
    characterId: 'mouse',
    name: 'Innocent',
    description: '순수. 전체 능력 +8% + 시작버프',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_mouse' },
    colors: {
      body: '#fef3c7',
      pants: '#fde68a',
      hair: '#fbbf24',
      accent: '#f59e0b',
      shoes: '#d97706',
      outfit: 'future_suit',
      accessoryType: 'crown',
      pattern: 'sparkle',
      patternColor: '#fbbf24',
      glowEffect: 'rainbow',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, hpBonus: 8, spdBonus: 8 },
    bonusSkill: {
      id: 'skill_innocent_buff',
      name: '순수의 축복',
      description: '게임 시작 시 10초간 모든 능력치 20% 증가',
      type: 'aura',
      effectParams: { value: 20, duration: 10 },
    },
  },

  // =============================================================================
  // DOZER (marco) - QA 엔지니어
  // =============================================================================
  {
    id: 'dozer_default',
    characterId: 'dozer',
    name: 'QA Tester',
    description: 'QA 테스터의 유니폼',
    rarity: 'common',
    unlockMethod: 'default',
    colors: {
      body: '#dc2626',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#ef4444',
      shoes: '#374151',
      outfit: 'business',
      accessoryType: 'glasses',
      pattern: 'none',
      glowEffect: 'none',
    },
    hasSpecialEffect: false,
  },
  {
    id: 'dozer_hunter',
    characterId: 'dozer',
    name: 'Bug Hunter',
    description: '버그 헌터. 공격력 +3%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_5' },
    colors: {
      body: '#22c55e',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#4ade80',
      shoes: '#374151',
      outfit: 'tactical',
      accessoryType: 'glasses',
      pattern: 'code',
      patternColor: '#22c55e',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 3 },
  },
  {
    id: 'dozer_lead',
    characterId: 'dozer',
    name: 'Test Lead',
    description: '테스트 리드. HP +4%',
    rarity: 'rare',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'perfect_10' },
    colors: {
      body: '#3b82f6',
      pants: '#1e1e1e',
      hair: '#1a1a2e',
      accent: '#60a5fa',
      shoes: '#374151',
      outfit: 'business',
      accessoryType: 'server_badge',
      pattern: 'stripes',
      patternColor: '#3b82f6',
      glowEffect: 'blue',
    },
    hasSpecialEffect: false,
    statBonus: { hpBonus: 4 },
  },
  {
    id: 'dozer_warrior',
    characterId: 'dozer',
    name: 'Quality Warrior',
    description: '품질 전사. 공격력 +5%, HP +5%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_15' },
    colors: {
      body: '#7c3aed',
      pants: '#4c1d95',
      hair: '#1a1a2e',
      accent: '#a78bfa',
      shoes: '#5b21b6',
      outfit: 'server_armor',
      accessoryType: 'helmet',
      pattern: 'circuit',
      patternColor: '#a78bfa',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 5, hpBonus: 5 },
  },
  {
    id: 'dozer_debugger',
    characterId: 'dozer',
    name: 'Debugger',
    description: '디버거. 공격력 +6%, 치명타 +4%',
    rarity: 'epic',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'kill_50000' },
    colors: {
      body: '#f97316',
      pants: '#c2410c',
      hair: '#1a1a2e',
      accent: '#fdba74',
      shoes: '#ea580c',
      outfit: 'tactical',
      accessoryType: 'glasses',
      pattern: 'binary',
      patternColor: '#f97316',
      glowEffect: 'purple',
    },
    hasSpecialEffect: false,
    statBonus: { atkBonus: 6, critBonus: 4 },
  },
  {
    id: 'dozer_crusher',
    characterId: 'dozer',
    name: 'Bug Crusher',
    description: '버그 크러셔. 공격력 +10%, HP +8% + 완드',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_20' },
    colors: {
      body: '#dc2626',
      pants: '#7f1d1d',
      hair: '#ef4444',
      accent: '#fca5a5',
      shoes: '#991b1b',
      outfit: 'server_armor',
      accessoryType: 'helmet',
      pattern: 'neon_lines',
      patternColor: '#dc2626',
      glowEffect: 'purple',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 10, hpBonus: 8 },
    bonusSkill: {
      id: 'skill_crusher_wand',
      name: '크러셔 완드',
      description: '버그를 박살내는 완드. 게임 시작 시 완드 Lv.1 획득',
      type: 'start_weapon',
      weaponType: 'wand',
      weaponLevel: 1,
      effectParams: { value: 10 },
    },
  },
  {
    id: 'dozer_perfect',
    characterId: 'dozer',
    name: 'Perfectionist',
    description: '완벽주의자. 공격력 +8%, 치명타 +10% + 폭발데미지',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'stage_30' },
    colors: {
      body: '#fbbf24',
      pants: '#92400e',
      hair: '#fde047',
      accent: '#fef3c7',
      shoes: '#ca8a04',
      outfit: 'future_suit',
      accessoryType: 'hologram',
      pattern: 'sparkle',
      patternColor: '#fbbf24',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 8, critBonus: 10 },
    bonusSkill: {
      id: 'skill_perfect_explosion',
      name: '완벽한 폭발',
      description: '적 처치 시 30% 확률로 폭발, 주변 적에게 데미지',
      type: 'on_kill',
      effectParams: { value: 50, chance: 30, radius: 100 },
    },
  },
  {
    id: 'dozer_exterminator',
    characterId: 'dozer',
    name: 'Exterminator',
    description: '말살자. 공격력 +12%, HP +10% + 범위폭발',
    rarity: 'legendary',
    unlockMethod: 'achievement',
    unlockCondition: { achievementId: 'mastery_dozer' },
    colors: {
      body: '#f97316',
      pants: '#c2410c',
      hair: '#fb923c',
      accent: '#fdba74',
      shoes: '#ea580c',
      outfit: 'server_armor',
      accessoryType: 'crown',
      pattern: 'neon_lines',
      patternColor: '#f97316',
      glowEffect: 'gold',
    },
    hasSpecialEffect: true,
    statBonus: { atkBonus: 12, hpBonus: 10 },
    bonusSkill: {
      id: 'skill_exterminator',
      name: '말살 프로토콜',
      description: '공격 시 15% 확률로 범위 폭발 발동',
      type: 'on_hit',
      effectParams: { value: 30, chance: 15, radius: 150 },
    },
  },
];

// =============================================================================
// 유틸리티 함수
// =============================================================================

// 스킨 ID로 조회
export const getSkinById = (id: string): Skin | undefined => {
  return SKINS.find(s => s.id === id);
};

// 캐릭터별 스킨 조회
export const getSkinsByCharacter = (characterId: PlayerClass): Skin[] => {
  return SKINS.filter(s => s.characterId === characterId);
};

// 등급별 스킨 조회
export const getSkinsByRarity = (rarity: SkinRarity): Skin[] => {
  return SKINS.filter(s => s.rarity === rarity);
};

// 기본 스킨 조회 (캐릭터별)
export const getDefaultSkin = (characterId: PlayerClass): Skin | undefined => {
  return SKINS.find(s => s.characterId === characterId && s.unlockMethod === 'default');
};

// 구매 가능한 스킨 조회
export const getPurchasableSkins = (): Skin[] => {
  return SKINS.filter(s => s.unlockMethod === 'purchase');
};

// 업적 해금 스킨 조회
export const getAchievementSkins = (): Skin[] => {
  return SKINS.filter(s => s.unlockMethod === 'achievement');
};

// 특정 업적으로 해금되는 스킨
export const getSkinByAchievement = (achievementId: string): Skin | undefined => {
  return SKINS.find(s =>
    s.unlockMethod === 'achievement' &&
    s.unlockCondition?.achievementId === achievementId
  );
};

// 전체 스킨 수
export const getTotalSkinCount = (): number => {
  return SKINS.length;
};

// 캐릭터별 스킨 수
export const getCharacterSkinCount = (characterId: PlayerClass): number => {
  return SKINS.filter(s => s.characterId === characterId).length;
};

// 스킨 카테고리 목록
export const SKIN_CATEGORIES: { id: SkinCategory; name: string }[] = [
  { id: 'default', name: 'Default' },
  { id: 'corporate', name: 'Corporate' },
  { id: 'retro', name: 'Retro' },
  { id: 'cyberpunk', name: 'Cyberpunk' },
  { id: 'matrix', name: 'Matrix' },
  { id: 'mastery', name: 'Mastery' },
];
